ClickHouse/clickhouse-java

src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java

There is a wrong getter getObject for timestamp value in ClickHouseResultSet.java. It return java.sql.Time instead java.sql.Timestamp

fix: getObject for timestamp value  in ClickHouseResultSet

---

src/main/java/ru/yandex/clickhouse/except/ClickHouseException.java

connecting to ```jdbc:clickhouse://localhost:8123``` using DataGrip
```
sql> show table
[1002] ClickHouse exception, code: 1002, host: localhost, port: 8123; null java.lang.NullPointerException
at ru.yandex.clickhouse.except.ClickHouseException.<init>(ClickHouseException.java:12)
at ru.yandex.clickhouse.except.ClickHouseUnknownException.<init>(ClickHouseUnknownException.java:11)
at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:60)
at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:27)
at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:439)
at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:79)
at …
```

fixed NPE in ClickHouseException

---

src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java

```setFetchDirection``` and ```setFetchSize``` are performance hints and may be ignored by the driver.
Throwing UnsupportedOperationException breaks RJDBC, see https://github.com/s-u/RJDBC/pull/11

jdbc driver should not fail on fetchSize hint

---

src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/response/ClickHouseResultBuilder.java
src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java

Changes that makes driver work correctly with Pentaho:
Added "statement"  attribute to ClickHouseResultSet and all constructors.
Added stub to  prepareStatement(String sql, int resultSetType, int resultSetConcurrency)

Ability to use driver with Pentaho Report Designer

---

src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java

If project includes a series of database drivers it gets a problem because ClickHouse driver tries to handle jdbc url to another DB.

Skip jdbc url to another DB

---

src/main/java/ru/yandex/clickhouse/ClickHouseDataSource.java
src/test/java/ru/yandex/clickhouse/ClickHouseDataSourceTest.java

[RFC 2732](http://www.ietf.org/rfc/rfc2732.txt) IPv6 Literal Addresses in URL's

Support IPv6 in JDBC URL

---

src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java

ленивая инициализация пула потоков, для того чтобы не расходовать процессорное время, т.к. метод вполне вероятно может и не вызываться.

Lazy init for scheduled executor service

---

src/main/resources/META-INF/services/java.sql.Driver

Этот файл позволит не делать Class.forName("ru.yandex.clickhouse.ClickHouseDriver"). Он не требуется в случае ClickHouseDataSource, но упрощает работу с другими DataSources. 
Подробности: https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html

introduce sql driver auto-load meta-file

---

src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseDataSource.java
src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java
src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/ClickhouseJdbcUrlParser.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
src/main/java/ru/yandex/clickhouse/settings/DriverPropertyCreator.java
src/main/java/ru/yandex/clickhouse/settings/DriverPropertyInfoAware.java
src/main/java/ru/yandex/clickhouse/util/TypeUtils.java
src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java
src/test/java/ru/yandex/clickhouse/integration/ArrayTest.java
src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java
src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java

1) Логика обработки jdbc url вынесена из ClickHouseDataSource в ClickhouseJdbcUrlParser (теперь не надо тащить DataSource в ConnectionImpl)
2) Реализован ClickHouseDriver.getPropertyInfo
3) ClickHouseDatabaseMetadata.getColumns переключен с 'desc table' на 'select from system.columns': теперь schemaPattern и tableNamePattern действительно работают. Как следствие jooq может генерировать java-классы для таблиц.
4) Исправлена проблема с зависанием DataGrip из https://github.com/yandex/clickhouse-jdbc/issues/21

Jdbc compliance improvements

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java

When setting extremes = true in connection properties, and using methods that return ResultSet, then empty row and extremes row are returned, that is not expected.
Issue appeared after bf9de10
As a solution forcibly disable extremes when using methods that return ResultSet

Forcibly disable extremes when using ResultSet

---

pom.xml
src/main/java/ru/yandex/clickhouse/ClickHouseExternalData.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatement.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java
src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java

Support of ClickHouse feature to send external data with query in a single http request.
[External data for query processing](https://clickhouse.yandex/reference_en.html#External%20data%20for%20query%20processing)

Ability to send external data along with query

---

src/main/java/ru/yandex/clickhouse/ClickhouseJdbcUrlParser.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java

The issue behind this fix is about missing properties after in case when both Properties and urlProperties are set.
See also `ClickhouseJdbcUrlParser#parseUriQueryPart(..)` https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/ClickhouseJdbcUrlParser.java#L66

(fix) Use Properties#getProperty(..) instead of #get(..) which loses defaults

---

src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java

In one of commits you change getting properties from `get` to `getProperty`. And it brakes setting properties with `ClickHouseProperties` class.
**Reason of this:**
In `getProperty` method there is checking that value `instanceof` String. But in `ClickHouseProperties` class you have properties(connection_timeout and other) that have time `int`, `boolean` etc. So for these values when you call `getProperty` method you will get `null` and default value would be set(like in test).
`String.valueOf` needed only for variables with primitive types, because objects can be null.

Fix setting properties for datasource with ClickHouseProperties class

---

src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java

for example, if you specify connection_timeout in jdbc url, it won't be set for HttpClient

jdbc url query parameters are not propagated into HttpClientBuilder

---

src/main/java/ru/yandex/clickhouse/response/ByteFragment.java
src/test/java/ru/yandex/clickhouse/response/ByteFragmentTest.java

Although this PR add supporting of  escaping and unescaping IOS-8859-1 characters, the escaping and unescaping should be based on Characters instead of Bytes. I think it should be improved in future.

escape and unescape non IOS-8859-1 characters

---

src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java

In documentation bool params have 0/1 values but in Java I should keep in mind that they need to be replaced with false/true values.
This patch allows using 0/1 in boolean params and correctly parse them.

Allow to set boolean params as 0/1

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/test/java/ru/yandex/clickhouse/integration/BatchInserts.java

Fixed that Clickhouse is looking for \N for NULL values, not "NULL".

---

src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java

I have added table types to getTableTypes() and getTables(), so that GUI tools can show the views in a separate folder from the tables.
To do that, I had to sort the table engines into 3 categories: Tables (engines that store data permanently), Views (engines that read data on-the-fly from other sources) and Other (engines that are neither tables nor views).

Implemented table types in database metadata

---

src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java
src/main/java/ru/yandex/clickhouse/util/ssl/NonValidatingTrustManager.java

Related to the issue #95 
The new driver properties are :
- ssl(true|false) to enable/disable ssl/tls
- sslrootcert an ssl/tls file name of the root ssl certificate
- sslmode the ssl verify mode (none|strict)

added the support of SSL/TLS connections.

---

src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java

Clickhouse preserve case of identifiers, but driver returns incorrect info about it

Fixed metadata methods about mixed-case identifiers

---

src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java

50ms too small for most environments,
10s - default connection timeout in Clickhouse core
https://github.com/yandex/ClickHouse/blob/8e5f92f02538d11151dac0aa45a75fdfb677a11c/dbms/src/Core/Defines.h#L11

Change default connection timeout 50ms -> 10s

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/response/ClickHouseResultBuilder.java
src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseStreamHttpEntity.java
src/test/java/ru/yandex/clickhouse/integration/TimeZoneTest.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStreamTest.java

getDate must not depend on timezone, so it must return Date wrapper of timestamp at start of the day in client timezone.

fix date parsing timezone

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseArrayUtil.java
src/test/java/ru/yandex/clickhouse/integration/ArrayTest.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseArrayUtilTest.java

Imagine function:
```java
void mapObject(PreparedStatement statement, List<Supplier<?>> getters) {
int count = 0;
for (Supplier<?> getter : getters) {
statement.setObject(++count, getter.get());
}
}
```
It works for any types except numeric arrays. Array of double will be serialized as `['1.23','4.56']`, but clickhouse expects no quoting of number (`[1.23,4.56]`).

Fix `ClickHousePreparedStatement.setObject(int, List<?>)` for Number

---

src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/ClickHouseConnectionTest.java

Now `getCatalog` always returns "default" even if specified database is not default. I fixed it and also added working `setCatalog` function.

fix getCatalog/setCatalog

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java

This adds an extra field to hold the return value from getUpdateCount, since it depends not only on whether the last statement was a select, but also needs to change after getMoreResults has been called.
Also getMoreResults will close the current result set (if any).

Fix issue #132

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseUtil.java
src/test/java/ru/yandex/clickhouse/ClickHouseUtilTest.java
src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java

There are two changes here:
* setString() adds an actual null value (\N) instead of the literal string 'NULL' when given a null parameter (fixes #123);
* A special case for null values is added to appendBoundValue (fixes #134).

#123 & #134: handle null string values for bind parameters.

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java

**Goal**
Simplifying debugging process
**Current situation** 
When debugging bind issues, a debugger is needed for determining, what was missed
**Solution**
Added index of missing placeholder for PreparedStatement in exception message

Add position of missing placeholder in PreparedStatement

---

src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
src/main/java/ru/yandex/clickhouse/util/TypeUtils.java
src/test/java/ru/yandex/clickhouse/util/TypeUtilsTest.java

Currently, we return isNull NO for all the columns in Click house table. This pull request checks the column type to be nullable and return the correct value.

Setting Nullable Metadata based of Column Type.

---

src/main/java/ru/yandex/clickhouse/BalancedClickhouseDataSource.java
src/main/java/ru/yandex/clickhouse/ClickHouseDataSource.java

Ordinary `ClickHouseConnection` does this, so for the sake of consistency & convenience, can we have this without resorting to casts on call sites?

Specialize on connection type in Balanced data source

---

src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
src/main/java/ru/yandex/clickhouse/util/TypeUtils.java
src/test/java/ru/yandex/clickhouse/util/TypeUtilsTest.java

Fixes:
1. Decimal digits - this now returns the number of fractional digits (as per the jdbc spec), and also works for nullable types.
2. Column size - the precision of the type, or the width in characters if a Date/DateTime

Metadata column fixes

---

src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java

ClickHouse displays Date and DateTime with integer value 0 as `0000-00-00` and `0000-00-00 00:00:00`, but the JDBC driver tries to parse them with SimpleDateFormat, returning weird dates.
This PR fixes the problem by returning Date and DateTime values that are zero using Java `null`

Fix display of zero-valued Date and DateTime values (return as Java null)

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java

Нужно для графауса. Там имя метрики хранится по частям, предварительно не конкатенируется и пишется в стрим по частям.

ClickHouseRowBinaryStream writeBytes function

---

src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java

previously 'nullable' field was hardcoded to 'columnNoNulls'

Make 'nullable' and 'is_nullable' metadata fields contain values of the same meaning

---

pom.xml

The `clickhouse-jdbc` strictly depends on such libraries like `com.google.guava` & `com.fasterxml.jackson.core` well known of its issues with backward/forward compatibilities.
I faced the classpath issues when tried to use `clickhouse-jdbc` with Apache Spark 2.3 (depends on Guava v14). Adding the dependency on shaded jar will solve the issue.
Such approach is widely used for the artifacts with dependcies on Guava, Jackson, etc. (see [google](https://search.maven.org/#search%7Cga%7C1%7Ccom.google.cloud.bigdataoss) provides shaded jars for its dependencies)

Maven shade plugin for uber jars with shaded dependencies

---

pom.xml

@serebrserg, the new version of shade plugin, as discussed in [pull-186](https://github.com/yandex/clickhouse-jdbc/pull/186)

adding maven-shade plugin for building the uber-jar with shaded depencies

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseArrayUtil.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseArrayUtilTest.java

Clickhouse supports insertion of array of nullables:
eg.
```
:) desc test_array_nullable_strings
DESCRIBE TABLE test_array_nullable_strings
┌─name─────────┬─type────────────────────┬─default_type─┬─default_expression─┐
│ date         │ Date                    │              │                    │
│ string       │ String                  │              │                    │
│ array_string │ Array(Nullable(String)) │              │                    │
│ s2           │ Nullable(String)        │              │                    │
│ a2           │ Array(String)           │              │                    │
│ a3           │ Array(Nullable(UInt16)) │              │                    │
└──────────────┴─────────────────────────┴──────────────┴────────────────────┘
:) insert into …
```

Support insert of array of nullables

---

src/main/java/ru/yandex/clickhouse/response/ByteFragmentUtils.java
src/test/java/ru/yandex/clickhouse/response/ByteFragmentUtilsTest.java

We faced an issue, when client is unable to deal with nan values from CH.
```
DESCRIBE TABLE uds_selector_results_Dc_60
┌─name───────────────┬─type───────────┬─default_type─┬─default_expression─┐
│ ts                 │ DateTime       │              │                    │
│ calculation_values │ Array(Float32) │              │                    │
└────────────────────┴────────────────┴──────────────┴────────────────────┘
Sample data:
┌──────────────────ts─┬─calculation_values────────────┐
│ 2018-04-09 15:44:00 │ [533,nan,0,270,250]           │
│ 2018-04-09 15:44:00 │ [1329,0.14597441,12,1002,994] │
│ 2018-04-09 15:42:00 │ [529,nan,0,269,248]           │
└─────────────────────┴───────────────────────────────┘
```
Current implementation fails with:
```
java.lang.NumberFormatException: For …
```

Add support for NaN values for floats and doubles

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatement.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java

To be able to use with e.g. chproxy (passing parameters such as `cache_namespace` etc)

Add support for arbitrary query params

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseCityHash.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseBlockChecksumTest.java

We've faced with incorrectly calculated checksum again (the last time was https://github.com/yandex/clickhouse-jdbc/pull/215).
The problem occurs when negative byte value is casted to int, i.e.
``0x9B`` --(cast to int)--> ``-101``
If we look at the ClickHouse sources
https://github.com/yandex/ClickHouse/blob/6df5d556e5af7aa95154374a1d601ac9c52a7dd7/contrib/libcityhash/src/city.cc#L139
we'll see that all operations are unsigned. It means that we'll obtain ``0x9B`` --(cast to uint32)--> ``155`` in the original code.
I've fixed it and now we have correct unsigned byte-to-int casting too :)
(Ticket in yandex tracker: https://st.yandex-team.ru/MARKETINFRA-3653)

Fix checksum calculation again

---

src/main/java/ru/yandex/clickhouse/BodyEntityWrapper.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseBlockChecksumTest.java

Hi,
To avoid issue #222, I propose to always send the query parameter in the HTTP body for all insert request.

#222 does't support large request (>16Kb)

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java

Replace a call to `toUpperCase` on the whole SQL query with a case-insensitive
match of the beginning of the string.
Converting the query to uppercase is wasteful, especially for "INSERT INTO" queries that can be particularly long.

Optimize isSelect, isDatabase and executeBatch by removing toUpperCase calls

---

pom.xml
src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSetMetaData.java
src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetMetaDataTest.java

ResultSetMetaData::isNullable method should return nullability of values in the designated column.
Currently, Clickhouse returns columnNoNulls for all columns including Nullable. This patch fixes the issue.

Returning true value of IsNullable from ClickHouseResultSetMetaData

---

src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
src/main/java/ru/yandex/clickhouse/response/StreamSplitter.java

Using clickhouse-jdbc in PAX-JDBC (Apache Karaf) fails, because ResultSet::isClosed throws UnsupportedOperationException.
I've try to implement this method.

Add ResultSet isClosed implementation

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java

To check fix please set breakpoint in constructor DefaultBHttpClientConnection on query execution.
You will see default buffer size 8kb.

Fix set default connection config for PoolingHttpClientConnectionManager

---

pom.xml
src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
src/test/java/ru/yandex/clickhouse/integration/RowBinaryStreamTest.java
src/test/java/ru/yandex/clickhouse/integration/TimeZoneTest.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStreamTest.java

Joda-time library is used only for calculation of daysSinceEpoch variable if one class. Removing this dependency gives less clutter for java 8 applications that use new date-time classes.

no joda dependency

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatement.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java

This simple PR fixes issue #264 by exposing a sendRowBinaryStream variant allowing custom ClickHouseQueryParam. I also did the same with sendNativeStream and sendStream for symmetry.

Ability to use sendRowBinaryStream with custom ClickHouseQueryParam

---

src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java

This very simple workaround for handling auth protected ingress / proxy
before a clickhouse instance. An even better solution would be to be
able to inject the Apache TargetAuthenticationStrategy, but since the
properties system is this simple I'm hesitant to add such logic for
handling something unrelated to clickhouse itself.
- Setting setHttpAuthorization() in the ClickhouseProperties will use
the value to set the HTTP "Authorization" header value. E.g.:
```java
properties.setHttpAuthorization("Basic " + Base64.encodeToString("username:password"));
ClickHouseDataSource dataSource = new ClickHouseDataSource(url, properties);
dbi = new DBI(dataSource);
try (Handle handle = dbi.open()) {
// do stuff.
}
```
Has been tested with HTTP ingress with enforced basic auth.

Add property for setting HTTP authorization header.

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java

the getConnectionManager will now return a logical default if the SslRootCertificate setting is empty.

use default context when sslrootcert is not set

---

src/main/java/ru/yandex/clickhouse/ClickhouseJdbcUrlParser.java

In internal Clickhouse over YT server implementation database may include dashes and asterisks, so we have to allow them.

Allow dashes and asterisks in jdbc url database part

---

src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java

Use daemon thread to schedule connection cleaner job so it won't interfere application shutdown.

run connection cleaner in daemon mode

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatement.java
src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java

I have implemented `ClickHousePreparedStatement.toString()`.
This method returns bound statement when `buildSql()` succeeds, otherwise unbound statement.

Enable to get a bound statement in ClickHousePreparedStatement

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatement.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStream.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
src/test/java/ru/yandex/clickhouse/integration/RowBinaryStreamTest.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStreamTest.java

I've added ClickHouseStatement.executeQueryClickhouseRowBinaryStream methods which return a ClickHouseRowBinaryInputStream to parse result. I've reused integration test in RowBinaryStreamTest.
A quick benchmark shows a performance gain lower than what I expected, maybe because of the little endian to big endian conversion. It also varies depending if the client code runs on the same machine as Clickhouse server.

Support for queries with RowBinary result

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java

Will have memory leak otherwise if clickhouse server is down

Batch rows should be cleared on clear batch. 

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java

Currently, the method `setQueryTimeout` at the Statement level does nothing (it comes from the JDBC interface)
Only the `setMaxExecutionTime` defined at the `ClickHouseProperties` class is currently implemented.
I change that, for having the timeout defined (if exist) at the statement level to overwrite the one at the properties level, even if it is a 0 (no timeout).
I also add the corresponding tests.

Implement query timeout at the statement level

---

pom.xml

This is caused by certain java / OS / test combinations recently started
failing to load the tests when running `failsafe` or `surefire` test
plugins.
```
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter
Caused by: java.lang.ClassNotFoundException: org.apache.maven.surefire.booter.ForkedBooter
```
Setting the noSystemClassLoader flag to false fixes this.

Set to use no system classloader in test plugins.

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java

Host name verifier should use **NoopHostnameVerifier** for sslMode **none**, to avoid ssl SAN failure:
`Certificate doesn't match any of the subject alternative names`

Utilize NoopHostnameVerifier for sslMode none

---

.travis.yml

Perhaps you want to use a different "reference" version, but we should at least test with 18.x, I think. Issue #319

Use latest ClickHouse server version for integration tests

---

src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java

Timezone is not initialised if none of `use_server_time_zone` and `use_time_zone` is set.
As consequence client gets parser exception when retrieving dates. See https://youtrack.jetbrains.com/issue/DBE-7776

Make sure timezone is initialized

---

src/main/java/ru/yandex/clickhouse/util/TypeUtils.java
src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetTest.java
src/test/java/ru/yandex/clickhouse/response/ClickHouseScrollableResultSetTest.java

1. Let's make sure we do not break too much stuff when fiddling with type mappings
2. Add missing UUID mapping (luckily, we do not use `Types.OTHER` for anything else)

Check class of ResultSet.getObject versus meta data #300

---

src/main/java/ru/yandex/clickhouse/BalancedClickhouseDataSource.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/test/java/ru/yandex/clickhouse/BalancedClickhouseDataSourceTest.java
src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java

- fix specified properties in 2nd para of BalancedClickhouseDataSource(url,clickhouseproperties) overwrited with default value
- fix incorrect pattern of multi host jdbc url with connections parameters
**issue reference:**
https://github.com/yandex/clickhouse-jdbc/issues/337

fix BalancedClickhouseDataSource contructor 2nd ClickhouseProperities parameter overwrited with default value, losing the custom settings

---

src/main/java/ru/yandex/clickhouse/PreparedStatementParser.java
src/test/java/ru/yandex/clickhouse/PreparedStatementParserTest.java

I get exception when on some specific queries where I have quote inside back quotes (or the opposite). The number of parameters was not well computed by the PrepareStatementImpl class.
This simple change fix the issue here, and I also add a new test.

Issue with quote inside back quotes, or back quotes inside quote in prepared statements

---

src/main/java/ru/yandex/clickhouse/util/TypeUtils.java

Without true detection of column size it's impossible to auto replicate to storage that supports only VARCHAR that needed to provide actual column size.

Fix getColumnsSize for LowCardinality(FixedString)

---

src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetTest.java

Some methods in ResultSet may produce NumberFormatException or NPE. 
This bugs was found when using jOOQ:
```
Caused by: java.lang.NumberFormatException: For input string: "\N"
at java.lang.NumberFormatException.forInputString (NumberFormatException.java:65)
at java.lang.Integer.parseInt (Integer.java:580)
at java.lang.Byte.parseByte (Byte.java:149)
at java.lang.Byte.parseByte (Byte.java:175)
at ru.yandex.clickhouse.response.ClickHouseResultSet.toByte (ClickHouseResultSet.java:494)
at ru.yandex.clickhouse.response.ClickHouseResultSet.getByte (ClickHouseResultSet.java:398)
at org.jooq.tools.jdbc.DefaultResultSet.getByte (DefaultResultSet.java:124)
at org.jooq.impl.CursorImpl$CursorResultSet.getByte (CursorImpl.java:748)
at org.jooq.impl.DefaultBinding$DefaultByteBinding.get0 …
```

Some methods in ResultSet may produce NumberFormatException or NPE

---

src/main/java/ru/yandex/clickhouse/except/ClickHouseExceptionSpecifier.java

On some cases, during the opening of a clickhouse connection, if the server is not up and we use the Server Timezone, we could have such error :
ERROR 2019-06-03 15:13:47,001 [main] ClickHouseExceptionSpecifier  - Unsupported ClickHouse error format, please fix ClickHouseExceptionSpecifier, message: Connect to localhost:18123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connexion refusée (Connection refused), error: For input string: "to localhost:18123 [localhost/0:0:0:0:0:0:0:1"
From what I see, the error parsing of the connection refused is generating a new exception.

ClickHouseUnknownException thrown on Connection refused

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java

Currently it will use GET requests to check for redirects, because Apache HTTP client does not support early responses, and because of difficulties with reproducing non-repeatable entities.
Off by default, can be turned on by setting `checkForRedirects` to `true`.

Add support for 307 redirects

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/ClickhouseJdbcUrlParser.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/test/java/ru/yandex/clickhouse/ClickhouseJdbcUrlParserTest.java

Support for URLs like `http://example.com/some/path?database=dbname`
Can be enabled by setting `usePathAsDb` to `false`. If set, `/some/path` will be treated as path instead of database name. Database name in turn can be given using `ClickHouseProperties` object, or with `?database=` parameter in URL.

Added support for paths in URL

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementParameter.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseValueFormatter.java

Following pipeline:
1.) String value = bool ? "1" : "0"
2.) Create new parameter holder for value
Replaced with:
bool ? trueParameter : falseParameter.
Got performance increase 10x times for setBoolean() sequential call.
@enqueue , FYI.

Speeded up setBoolean 10x times

---

src/main/java/ru/yandex/clickhouse/response/ByteFragmentUtils.java
src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
src/test/java/ru/yandex/clickhouse/response/ByteFragmentUtilsTest.java
src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetTest.java

It makes array parser recursive (we aware of the array depth in advance, and leaf nodes are always on the same level).
Just in case, the max depth is restricted: ≤ 32.

Nested arrays support

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseValueFormatter.java
src/test/java/ru/yandex/clickhouse/ClickHousePreparedStatementParameterTest.java

If a collection is passed in it will automatically be converted
into an array literal. However, like for normal arrays, this
generated string must not be quoted again when being
inserted into a prepared statement.
ClickHouseValueFormatter#formatObject (L155)
will happy convert Collections into appropriate array
literals but these will be quoted again and then rejected
by the Clickhosue server as a true array instead of a
string literal is expected.

Doesn't quote generated arrays if a collection was given.

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStream.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStreamTest.java

`ClickHouseRowBinaryInputStream` can't read FixedString(n) and throw exception in this case, therefore the functionality for reading FixedString(n) has been added.
this [issue](https://github.com/ClickHouse/clickhouse-jdbc/issues/394)

read FixedString from BinaryInputStream

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseValueFormatter.java
src/test/java/ru/yandex/clickhouse/ClickHousePreparedStatementParameterTest.java

Boolean -> ClickHousePreparedStatementParameter using ClickHousePreparedStatementParameter.fromObject produces value with single quotes (is recognized as String by ClickHouse, not as Uint8, as it should be)

Bugfix for Boolean type formatting

---

src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java
src/test/java/ru/yandex/clickhouse/integration/ErrorsTest.java

[This](https://github.com/ClickHouse/ClickHouse/pull/9274) and [these](https://github.com/ClickHouse/ClickHouse/pull/9449) changes are backwards incompatible and broke the tests

fix some test

---

src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java

We faced an issue where the client was getting broken pipe error while sending a request to insert data into clickhouse. We figured that the server had <keep_alive_timeout>3</keep_alive_timeout> and client (driver) was trying to keep the connection alive for 30 seconds (default). 
Ideally, client shouldn't try to use it's own settings for keep-alive when server responds with a different value. If server doesn't respond with a value of timeout, TCP defaults should be used. 
The chances of getting this issue are more when data is written as an InputStream as HttpClient can't retry that request due to stream processing.
After we fixed and deployed this change locally, we haven't received any broke pipe issues.

Issue with driver not honoring the server keep-alive timeout settings

---

src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java

support Explain queries, isSelect must be true for them
"explain select 42"
fixes: https://github.com/ClickHouse/ClickHouse/issues/18397

support Explain queries, isSelect must be true for them

---

src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
src/test/java/ru/yandex/clickhouse/integration/ClickHouseDatabaseMetadataTest.java

Fix for #480
Column comments have been available for some years in ClickHouse server, so I assume it is safe to refer to the column. If we want to support older server versions, please give me a hint for which minimum version to check.

Make column comments available via DatabaseMetaData REMARKS

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStreamTest.java

Currently there's a function `writeUInt64Array` with `long[]` parameter. But `writeUInt64` itself supports `UnsignedLong` as well.
Add this overloaded method also for writing UInt64 arrays.

Write UInt64 Array also as UnsignedLong type

---

src/main/java/ru/yandex/clickhouse/util/ClickHouseLZ4OutputStream.java

Not sure if this is wanted / useful for others.
But in our case, we aren't using the full JDBC library, just this class to compress the `INSERT` queries (because we're doing some batching of records, then push as one batch to a HTTP output stream).
Because of also other buffers, it is useful to know how much data is buffered into the LZ4 compression buffers, preventing having to call `flush()` regularly.

Expose the pointer for the LZ4 Compression buffer

---

src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/main/java/ru/yandex/clickhouse/PreparedStatementParser.java
src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java

Fix for #495 It's not beautiful, but should fix the bug (at least the tests are green). I expect some major clean-up / refactoring in `ClickHousePreparedStatementImpl` and friends after 0.2.5 (e.g. via #418 and perhaps #535)

Static null parameters for non-batch PreparedStatement

---

src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
src/test/java/ru/yandex/clickhouse/response/ClickHouseResultBuilderTest.java

```
/**
* Maps the given <code>ResultSet</code> column label to its
* <code>ResultSet</code> column index.
*
* @param columnLabel the label for the column specified with the SQL AS clause.  If the SQL AS clause was not specified, then the label is the name of the column
* @return the column index of the given column name
* @exception SQLException if the <code>ResultSet</code> object
* does not contain a column labeled <code>columnLabel</code>, a database access error occurs
*  or this method is called on a closed result set
*/
int findColumn(String columnLabel) throws SQLException;
```

implement ResultSet findColumn() method issue#525

---

src/main/java/ru/yandex/clickhouse/BalancedClickhouseDataSource.java

It is very difficult to debug connect failures while using BalancedClickhouseDataSource as the code swallows all connect exceptions.
This adds a log so that it's actually possible to figure out why connect is failing for one or more JDBC URLs. I wasn't totally sure what the ethos is in this project WRT how much to log, so I started at debug, but would be happy to increase the log level.

Log connect failures in BalancedClickhouseDataSource

---

.github/workflows/build.yml
.github/workflows/verify.yml
src/test/java/ru/yandex/clickhouse/ClickHouseContainerForTest.java
src/test/java/ru/yandex/clickhouse/integration/ErrorsTest.java
src/test/java/ru/yandex/clickhouse/integration/NativeStreamTest.java

* fix test case failure found on latest ClickHouse release
* add new workflow to verify specific branch/pull request
* add 19.14 in regression and fix failed test cases accordingly

Fix build break and add 19.14 in regression

---

README.md
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/Writer.java
src/main/java/ru/yandex/clickhouse/domain/ClickHouseCompression.java
src/test/java/ru/yandex/clickhouse/integration/StreamSQLTest.java

I need to upload gzipped files to CH from my JDBC application without decompression them at a client side.
this PR implements this: 
```
.write() // Write API entrypoint
.table("default.my_table") // where to write data
.option("format_csv_delimiter", ";") // specific param
.data(new File("/path/to/file.csv.gz"), ClickHouseFormat.CSV, ClickHouseCompression.gzip) // specify input
.send();
```

ability to send compressed files/streams

---

pom.xml
src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java
src/test/java/ru/yandex/clickhouse/BalancedClickhouseDataSourceTest.java
src/test/java/ru/yandex/clickhouse/ClickHouseContainerForTest.java
src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java
src/test/java/ru/yandex/clickhouse/integration/ClickHouseConnectionImplTest.java
src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java
src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java
src/test/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilderTest.java
src/test/resources/ru/yandex/clickhouse/users.d/foo.xml
src/test/resources/ru/yandex/clickhouse/users.d/oof.xml

Use Basic auth for credentials instead of query params

---

src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetTest.java

Restore public getColumnNames method

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/Writer.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/StreamSQLTest.java

* Explicitly add "compress" query parameter according to given option
* Avoid "Content-Encoding" header when compression option is "none"

Fix issue #591

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java

it's optimizations used for write string;

Feat: ClickHouseRowBinaryStream add writeBytes function

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseCookieStoreProvider.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/util/ClickHouseCookieStoreProviderTest.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilderTest.java

Allows to share same cookie store among http clients of same database. This feature allows users to use [AWS ALB ](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/sticky-sessions.html) sticky sessions.
With the help of sticky sessions, we can direct all the queries from a given client to same CH node. We can achieve `read your writes` consistency at each client level (Client will always see the writes it made as we are hitting the same CH node - assuming other CH properties are appropriately configured).

Shared cookie store

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ClickHouseLargeNumberTest.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ClickHouseMapTest.java

Add 3 more query parameters: `allow_experimental_bigint_types`, `allow_experimental_map_type`, and `join_algorithm`.

Add more query parameters

---

.github/workflows/benchmark.yml
.gitignore
clickhouse-benchmark/src/main/java/tech/clickhouse/benchmark/ClientState.java
clickhouse-benchmark/src/main/java/tech/clickhouse/benchmark/Insertion.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
clickhouse-jdbc/src/main/javacc/ClickHouseSqlParser.jj
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/jdbc/parser/ClickHouseSqlParserTest.java

* enable batch processing in Statement
```java
try (Statement s = connection.createStatement()) {
s.addBatch("select 1; select 2"); // same as s.addBatch("select 1"); s.addBatch("select 2");
s.addBatch("select 3");
...
s.executeBatch();
}
```
* arbitray sql in PreparedStatement
```java
try (PreparedStatement s = connection.prepareStatement("alter table my_table update value=? where key=2")) {
s.setInt(1, 233);
s.addBatch(); // addBatch(String) will result in SQLException according to JDBC spec
...
s.executeBatch();
}
```

Batch processing

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/domain/ClickHouseFormat.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStream.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStreamTest.java

```java
try (ClickHouseStatementImpl s = (ClickHouseStatementImpl) connection.createStatement()) {
ClickHouseRowBinaryInputStream input = s.executeQueryClickhouseRowBinaryStream("select * from my_table");
List<ClickHouseColumnInfo> columns = input.getColumns();
...
}
```

Add RowBinaryWithNamesAndTypes

---

clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ClickHouseMapTest.java

Will add integration test into ClickHouse repo so that we don't have to do this ever again.

Fix build break by disable testMaps for 21.4

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ClickHouseConnectionImplTest.java

* only ignore database parameter when given DDL contains `DATABASE` keyword
* change current database of Statement/PreparedStatement as needed
* add unit test to address regression issue

Fix issue #648 introduced in 0.3.1

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java

In the addBatch method, add parsedStmt.hasValues() check to ensure that the query of the form 'INSERT INTO ... SELECT' will be executed.

In the addBatch method, add parsedStmt.hasValues() check to ensure that the query of the form 'INSERT INTO ... SELECT' will be executed

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java

Fixes https://github.com/ClickHouse/clickhouse-jdbc/issues/657

Return correct value from getAutoCommit

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java

Transactions are not supported, so `setAutoCommit(false)` should fail,
as it does not provide the isolation or rollback-ability requested by
the caller.
`commit()` and `rollback()` should fail in auto-commit mode (this is
what PostgreSQL JDBC driver does).

Return proper error when user tries to enable transactions

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/NativeStreamTest.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/RowBinaryStreamTest.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStreamTest.java

row_binary_fixed_string support

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java

Added an explicit indication of the text/plain content type with UTF-8 encoding for an SQL query in MultipartEntityBuilder, otherwise the text/plain content type with ISO_8859_1 encoding is used and Latin letters turn into'??????'

Fixed the content type in requests with external data

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseVersionNumberUtil.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ClickHouseLargeNumberTest.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/util/ClickHouseVersionNumberUtilTest.java

Fix NPE when initializing connection

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java

It looks like the log level is `INFO` for the driver registration. If you look at most JDBC implementations, they use DEBUG in this exact case since the registration is expected when we load ClickhouseDriver in the runtime.

Change log level for driver registration

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java

`dataTransferTimeout` property was only used to set `max_execution_time` as a sum of `socket_timeout` and `dataTransferTimeout`. From _6851fd74c06174819aca842a1634c2abc33e99b5_ behavior changed: `max_execution_time` is set as `max_execution_time`, has nothing to do with socket or data transfer timeouts.
(and also there are some misleading old docs about it)

Remove redundant data transfer timeout property

---

.github/workflows/benchmark.yml
.github/workflows/release_3rd_party_libs.yml
.github/workflows/timezone.yml
.github/workflows/verify.yml
third-party-libraries/io.grpc/pom.xml
third-party-libraries/org.roaringbitmap/pom.xml
third-party-libraries/pom.xml

* use consistent version for all repackaged 3rd party libs
* update group id to `com.clickhouse` instead of `tech.clickhouse`
* remove useless build steps
* add new job to release 3rd party libs

Update build config for repackaging 3rd party libs

---

clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseBitmap.java
clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseBitmap.java

Fix release error:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
at ru.yandex.clickhouse.integration.ClickHouseBitmapTest.testRoaringBitmap64(ClickHouseBitmapTest.java:194)
```

Fix missing api

---

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseResultSet.java

NullPointerException happens when retrieve null DateTime from clickhouse.
clickhouse-jdbc version is :
<dependency>
<groupId>com.clickhouse</groupId>
<artifactId>clickhouse-jdbc</artifactId>
<version>0.3.2</version>
</dependency>

Fix NullPointerException

---

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaData.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java

`comment` column doesn't exist in `system.tables` when version < 21.6 as far as I confirmed.

Fix version check for system.tables.comment column in DatabaseMetaData.getTables

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValues.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseBoolValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseStringValue.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseValuesTest.java
clickhouse-client/src/test/java/com/clickhouse/client/data/ClickHouseBoolValueTest.java
clickhouse-client/src/test/java/com/clickhouse/client/data/ClickHouseStringValueTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java

* Fix #848 
* Throw `IllegalArgumentException` for invalid boolean value
* Improve type conversion and add more tests
| Type | Value | Boolean Value | Remark |
| ---- | ------ | -------------- | -------- |
|  Number | `1` | true | same for 1.000 |
|   | `0` | false | same for 0.000 |
|  Character | `T`, `Y`, `1` | true | case-insensitive |
|   | `F`, `N`, `0` | false | case-insensitive |
|  String | `true`, `yes`, `1` | true | case-insensitive |
|   | `false`, `no`, `0` | false | case-insensitive, null and empty string are treated as false |

Enhance Bool support

---

README.md
clickhouse-client/README.md
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseOffsetDateTimeValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseRowBinaryProcessor.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseByteArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseDoubleArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseFloatArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseIntArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseLongArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseShortArrayValue.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseUtilsTest.java
clickhouse-jdbc/README.md
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/AbstractPreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/InputBasedPreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/TableBasedPreparedStatement.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
examples/grpc/pom.xml
examples/jdbc/pom.xml
pom.xml

* Bump version
* Fix issue of writing Date32 value in RowBinary format
* Fix OffsetDateTime parsing error
* Fix NumberFormatException when parsing primitive array with null value
* Optimize PreparedStatement by treating `insert into table values(?,?)` as `insert into table` for better performance and less memory consumption on client side

Prepare patch6

---

clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/response/ClickHouseResponseGsonDeserializer.java
clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/ClickHouseStatementImplTest.java

Hi, it seems, that I missed one corner case in https://github.com/ClickHouse/clickhouse-jdbc/pull/862
If there is NaN in response it is written as null in json "data", and my deserializer didn't check that.
This time I ran my fix through our internal tests (with wide selection of prod-like queries), and it seems that now response is deserialized like it used to before.
Example with NaN:
```
String connectionUrl = "jdbc:clickhouse://localhost:8123/default";
ClickHouseConnection clickHouseConnection = (ClickHouseConnection) DataSourceUtils.getConnection(
new ClickHouseDataSource(connectionUrl, new ClickHouseProperties()));
ClickHouseResponse clickHouseResponse = clickHouseConnection.createStatement().executeQueryClickhouseResponse("SELECT 0/0 AS n");
```
It failed with exception:
``` …
```

fixed issue with null in legacy driver's json response deserializer + test

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseEnum.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValues.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseDoubleValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseFloatValue.java
clickhouse-client/src/test/java/com/clickhouse/client/data/ClickHouseDoubleValueTest.java
clickhouse-client/src/test/java/com/clickhouse/client/data/ClickHouseFloatValueTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseResultSetTest.java

Avoid losing precision when converting Float and Double to BigDecimal

---

clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseRenameMethod.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseRowBinaryProcessor.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseTabSeparatedProcessor.java
clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
clickhouse-client/src/test/java/com/clickhouse/client/config/ClickHouseRenameMethodTest.java

Closes #912.
New option `rename_response_column`(defaults to `NONE`):
Option | Original Column Name | New Column Name |
------- | ---------------------- | ------------------- |
NONE | `a.b.c d_e`                    | `a.b.c d_e`              |
REMOVE_PREFIX | `a.b.c d_e`                    | `c d_e`              |
TO_CAMELCASE | `a.b.c d_e`                    | `a.b.cDE`              |
TO_CAMELCASE_WITHOUT_PREFIX | `a.b.c d_e`                    | `cDE`              |
TO_UNDERSCORE | `a.b.c d_e`                    | `a.b.c_d_e`              |
TO_CAMELCASE_WITHOUT_PREFIX | `a.b.c d_e`                    | `c_d_e`              |

Add new option for rename response column names

---

.github/workflows/third_party_libs.yml
.github/workflows/timezone.yml
pom.xml
third-party-libraries/pom.xml

This is a follow-up of #936.
CI will fail until we get this PR merged and release 3rd party libs 1.2.0.

Upgrade gRPC libs

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java
clickhouse-client/src/main/java/com/clickhouse/client/stream/AbstractByteArrayInputStream.java
clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java

Deserialization will fail when `response_buffering` is set to `PERFORMANCE` and `compress` is `true`. Regression case has been enhanced to ensure it won't happen again.

Fix deserialization issue in performance mode

---

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDataSource.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDataSourceTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseResultSetTest.java

Fix custom properties lost issue and add more tests

---

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/SqlExceptionUtils.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/InputBasedPreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/TableBasedPreparedStatement.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java

Stop throwing exception when executing empty batch

---

clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseByteArrayValue.java
clickhouse-client/src/test/java/com/clickhouse/client/data/ClickHouseRowBinaryProcessorTest.java
clickhouse-client/src/test/java/com/clickhouse/client/data/array/ClickHouseByteArrayValueTest.java

Fixes number cast exception for ClickHouseArrayValue with Boolean[]

Fixes number cast exception for ClickHouseArrayValue with Boolean[]

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java
clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcChannelFactory.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/HttpUrlConnectionImpl.java
clickhouse-http-client/src/main/java11/com/clickhouse/client/http/HttpClientConnectionImpl.java

Will address cli and grpc clients in the future, if needed.

Add use_no_proxy option to avoid using proxy

---

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/InputBasedPreparedStatement.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java

Use unbounded queue for batch insert

---

clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseDateTimeValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseDateValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseOffsetDateTimeValue.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java

apply timezone to datetime default value

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNode.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseResponseSummary.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java

Remove sessionId before cancelling query

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseUtils.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseArray.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseConnection.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaData.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseResultSet.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseResultSetMetaData.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/JdbcConfig.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/JdbcTypeMapping.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseParameterMetaData.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/InputBasedPreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/TableBasedPreparedStatement.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java

* [BREAKING CHANGE] Refactor JdbcTypeMapping by making it extensible
* Add new JDBC option `dialect` and sample implementation AnsiTypeMapping (dialect=ansi)

Refactor JdbcTypeMapping by making it extensible

---

.github/workflows/build.yml
.github/workflows/nightly.yml
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseArraySequence.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseByteBuffer.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseColumn.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseDataProcessor.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseDataType.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValues.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseRowBinaryProcessor.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseTabSeparatedProcessor.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseByteArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseDoubleArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseFloatArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseIntArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseLongArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseShortArrayValue.java
clickhouse-client/src/main/java/com/clickhouse/client/stream/AbstractByteArrayInputStream.java
clickhouse-client/src/main/java/com/clickhouse/client/stream/AbstractByteBufferInputStream.java
clickhouse-client/src/main/java/com/clickhouse/client/stream/IterableMultipleInputStream.java
clickhouse-client/src/main/java/com/clickhouse/client/stream/NonBlockingInputStream.java
clickhouse-client/src/main/java/com/clickhouse/client/stream/WrappedInputStream.java
clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java

Deserialization of primitive arrays is now twice faster than before, and it also benefits the upcoming Native data format.
```
Benchmark                              (client) (connection)  (statement)  (type)   Mode  Cnt  Score   Error  Units
Query.selectArrayOfUInt16  v0.3.3-SNAPSHOT             reuse     prepared  object  thrpt   20  3.066 ? 0.208  ops/s
Query.selectArrayOfUInt16  v0.3.2-patch11              reuse     prepared  object  thrpt   20  1.380 ? 0.079  ops/s
Query.selectArrayOfUInt16  clickhouse-native-jdbc      reuse     prepared  object  thrpt   20  0.720 ? 0.102  ops/s
```
```
Benchmark                          (client)    (connection)  (statement)  (type)   Mode  Cnt    Score   Error  Units
Query.selectInt8    v0.3.3-SNAPSHOT(Native)           reuse     prepared  object …
```

Optimize reads for array values

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseInputStream.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseOutputStream.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseSimpleResponse.java
clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseStreamResponse.java
clickhouse-client/src/main/java/com/clickhouse/client/stream/RestrictedInputStream.java
clickhouse-client/src/test/java/com/clickhouse/client/stream/InputStreamImplTest.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHousePreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/StreamBasedPreparedStatement.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java

Take format clause as hint for stream-based insertion.
```java
try (PreparedStatement ps = conn.preparedStatement("insert into mytable(col1,col2,col3) format CSV")) {
ps.setString(1, "1,2,3");
ps.addBatch();
ps.setBinaryStream(1, new ByteArrayInputStream("4,5,6".getBytes()));
ps.addBatch();
ps.setObject(1, new ClickHouseWriter() { // callback runs in a separate worker thread
@Override
public void write(ClickHouseOutputStream out) throws IOException {
out.write("7,8,9".getBytes());
}
});
ps.addBatch();
ps.setObject(1, new File("/tmp/my.csv"));
ps.addBatch();
ps.executeBatch();
}
```

Add stream-based prepared statemenet

---

clickhouse-benchmark/pom.xml
clickhouse-cli-client/pom.xml
clickhouse-grpc-client/pom.xml
clickhouse-http-client/pom.xml
clickhouse-jdbc/pom.xml
clickhouse-r2dbc/pom.xml
examples/grpc/pom.xml
examples/grpc/src/main/java/com/clickhouse/examples/jdbc/Main.java
examples/jdbc/pom.xml
examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java
pom.xml

Create source jars and update examples

create source jar and update examples

---

CHANGELOG.md

We want to use CHANGELOG.md as a source of truth across different communication channels (the documentation website, ClickHouse UI, etc.)
To make it portable, CHANGELOG must follow a pre-defined structure and format,  outlined in the current PR.
We still can keep https://github.com/ClickHouse/clickhouse-java/releases section, but it's better to link the CHANGELOG to a release instead of copying the content in several places.

add changelog.md

---

CHANGELOG.md
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseArraySequence.java
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataType.java
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDeserializer.java
clickhouse-data/src/main/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessor.java
clickhouse-data/src/main/java/com/clickhouse/data/value/array/ClickHouseLongArrayValue.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseColumnTest.java
clickhouse-data/src/test/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessorTest.java
clickhouse-data/src/test/java/com/clickhouse/data/format/ClickHouseTabSeparatedProcessorTest.java
clickhouse-data/src/test/java/com/clickhouse/data/value/BaseDataProcessorTest.java

fix incorrect nested array value

---

CHANGELOG.md
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/SqlExceptionUtils.java

Fix potential endless loop when batch update failed

Fix potential endless loop when batch update failed

---

CHANGELOG.md
clickhouse-data/src/main/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessor.java
clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseNestedValue.java
clickhouse-data/src/test/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessorTest.java
clickhouse-data/src/test/java/com/clickhouse/data/value/ClickHouseNestedValueTest.java

Fix deserialization issue of Nested data type.

fix deserialization issue of Nested data type

---

.github/workflows/nightly.yml
.github/workflows/release.yml
.gitignore
README.md
clickhouse-benchmark/pom.xml
clickhouse-cli-client/README.md
clickhouse-client/README.md
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseNodeTest.java
clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
clickhouse-data/README.md
clickhouse-jdbc/README.md
clickhouse-r2dbc/README.md
examples/client/pom.xml
examples/client/src/main/java/com/clickhouse/examples/jdbc/Main.java
examples/jdbc/pom.xml
examples/r2dbc/clickhouse-r2dbc-spring-webflux-sample/pom.xml
pom.xml

prepare 0.4.1 release

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java

- Overloaded the `ClickHouseClient.newInstance` method to allow supplying default `ClickHouseCredentials` during creation.
Given how convenient calling `ClickHouseClient.newInstance(..)` is, it makes sense to overload and allow the user to supply default credentials.

Add Credentials Overload for Client

---

CHANGELOG.md
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseRequest.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseRequestTest.java

Repsect node-specific credentials.

Repsect node-specific credentials

---

CHANGELOG.md
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaData.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/JdbcConfig.java

Add JDBC option `externalDatabase`(true or false, defaults to true) to exclude external databases from metadata.

new JDBC option to exclude external databases from metadata

---

CHANGELOG.md
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseTransaction.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseConnection.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/JdbcTransaction.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/parser/ClickHouseSqlStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/parser/StatementType.java
clickhouse-jdbc/src/main/javacc/ClickHouseSqlParser.jj
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseConnectionTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/parser/ClickHouseSqlParserTest.java

Support `BEGIN TRANSACTION`, `COMMIT`, and `ROLLBACK` in JDBC driver.

TCL support

---

CHANGELOG.md
README.md
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClientBuilder.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNode.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNodeManager.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNodes.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseRequest.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseRequestTest.java
clickhouse-client/src/test/resources/containers/clickhouse-server/config.d/ports.xml
clickhouse-client/src/test/resources/containers/clickhouse-server/users.d/users.xml
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseFreezableMap.java
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseUtils.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseFreezableMapTest.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseUtilsTest.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseConnection.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/JdbcConfig.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseJdbcUrlParser.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseConnectionTest.java

Centralized configuration for JDBC driver.

Centralized configuration for JDBC driver

---

CHANGELOG.md
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/TableBasedPreparedStatement.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java

Only throw BatchUpdateException for statements for read.

Only throw BatchUpdateException for statements for read

---

.github/workflows/third_party_libs.yml
third-party-libraries/org.congocc/pom.xml
third-party-libraries/org.congocc/src/main/java/org/congocc/DummyClass.java
third-party-libraries/pom.xml

switch to CongoCC

---

clickhouse-client/pom.xml
clickhouse-data/src/main/java/com/clickhouse/data/stream/Lz4InputStream.java
pom.xml

Fix issue when reading from Lz4InputStream using text-base data format. This closes ClickHouse/ClickHouse#48446 and dbeaver/dbeaver#19681.

Fix issue when reading from Lz4InputStream using text-base data format

---

CHANGELOG.md
pom.xml

Bump dependencies and rollback flatten plugin to 1.2.7.

Bump dependencies and rollback flatten plugin to 1.2.7

---

CHANGELOG.md
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImplTest.java

Disable SQL rewrite for DELETE statement in ClickHouse 23.3+

Disable SQL rewrite for DELETE statement in ClickHouse 23.3+

---

CHANGELOG.md
clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/ClickHouseCommandLineResponse.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseSimpleResponse.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseStreamResponse.java
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataProcessor.java
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseSimpleRecord.java
clickhouse-data/src/main/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessor.java
clickhouse-data/src/main/java/com/clickhouse/data/format/ClickHouseTabSeparatedProcessor.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseSimpleRecordTest.java

refactor data processors and response classes to ensure input stream remain intact before first read

refactor data processors and response classes to ensure input stream remain intact before first read

---

clickhouse-data/src/main/java/com/clickhouse/data/format/BinaryDataProcessor.java
clickhouse-data/src/main/java/com/clickhouse/data/format/TextDataProcessor.java

The `cache` should be thread-safe since it is shared to multi-threads, otherwise may fail w/ the following errors
```
(fv-az617-691.33ka01qfponuxnhx0mx0ps1wwf.jx.internal.cloudapp.net executor driver): java.util.ConcurrentModificationException
at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1135)
at com.clickhouse.data.format.BinaryDataProcessor$DateTime32SerDe.of(BinaryDataProcessor.java:219)
at com.clickhouse.data.format.ClickHouseRowBinaryProcessor.getDeserializer(ClickHouseRowBinaryProcessor.java:341)
at com.clickhouse.data.ClickHouseDataProcessor$DefaultSerDe.<init>(ClickHouseDataProcessor.java:89)
at com.clickhouse.data.ClickHouseDataProcessor.getInitializedSerDe(ClickHouseDataProcessor.java:286)
at com.clickhouse.data.ClickHouseDataProcessor.lambda$records$0(ClickHouseDa …
```

Use ConcurrentHashMap for DataType SerDe cache

---

.github/workflows/analysis.yml
.github/workflows/build.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
CONTRIBUTING.md
pom.xml

Bump dependencies and upgrade to 23.3 for regression.

bump dependencies and upgrade to 23.3 for regression

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java

@zhicwu Sorry, there is something wrong with my local commits in #1336 and lose `reusable` change. The benchmark in #1336 runs with `reusable` = true.
This Pr simple make apache http client reusable.

make apache http client reusable

---

CHANGELOG.md
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDeserializer.java
clickhouse-data/src/main/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessor.java
clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseArrayValue.java
clickhouse-data/src/main/java/com/clickhouse/data/value/array/ClickHouseBoolArrayValue.java
clickhouse-data/src/main/java/com/clickhouse/data/value/array/ClickHouseByteArrayValue.java
clickhouse-data/src/main/java/com/clickhouse/data/value/array/ClickHouseDoubleArrayValue.java
clickhouse-data/src/main/java/com/clickhouse/data/value/array/ClickHouseFloatArrayValue.java
clickhouse-data/src/main/java/com/clickhouse/data/value/array/ClickHouseIntArrayValue.java
clickhouse-data/src/main/java/com/clickhouse/data/value/array/ClickHouseLongArrayValue.java
clickhouse-data/src/main/java/com/clickhouse/data/value/array/ClickHouseShortArrayValue.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java

Remove false optimization to fix deserialization issue of nested array in other nested types.

Fix deserialization issue of nested array in other nested types

---

CHANGELOG.md
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/JdbcConfig.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseConnectionTest.java

Change default databaseTerm to catalog.

change default databaseTerm to catalog

---

clickhouse-client/src/test/resources/containers/clickhouse-server/config.d/ports.xml

Remove unsupported setting

---

third-party-libraries/org.congocc/pom.xml

Fix build failure of congocc caused by congo-cc/congo-parser-generator#37.

Fix build failure of congocc

---

.github/workflows/build.yml
clickhouse-grpc-client/src/test/java/com/clickhouse/client/grpc/ClickHouseGrpcClientTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java

* disabled two more gRPC test cases due to its poor performance
* stop using `test_shard_localhost` in tests as it's gone in most recent ClickHouse releases
* enhance test using union all to avoid ordering issue in ClickHouse 22.8+

Fix CI failure

---

CHANGELOG.md
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseUtils.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseColumnTest.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseUtilsTest.java
clickhouse-data/src/test/java/com/clickhouse/data/stream/InputStreamImplTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseResultSetTest.java

Resolves https://github.com/ClickHouse/clickhouse-java/issues/1389
Skipping of whitespace is prevented when processing a section within brackets.
I had to change some other tests that were failing now, but don't think it would break anything else. Not sure why whitespace is removed in the first place?

[bug #1389] Resolve processing Nested column type in combination with AggregateFunction

---

CHANGELOG.md
clickhouse-client/src/main/java/com/clickhouse/client/AbstractSocketClient.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseSocketFactory.java
clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
clickhouse-client/src/test/java/com/clickhouse/client/AbstractSocketClientTest.java
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseUtils.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseUtilsTest.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
clickhouse-http-client/src/test/java/com/clickhouse/client/http/ApacheHttpConnectionImplTest.java

Support custom socket factory as requested in #1391.

support custom socket factory

---

.github/workflows/build.yml
CHANGELOG.md
clickhouse-benchmark/src/main/java/com/clickhouse/benchmark/client/ClientState.java
clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/ClickHouseCommandLineClient.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNodes.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseTransaction.java
clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
clickhouse-client/src/test/java/com/clickhouse/client/AbstractClientTest.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseClientTest.java
clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcChannelFactory.java
clickhouse-grpc-client/src/test/java/com/clickhouse/client/grpc/ClickHouseGrpcChannelFactoryTest.java
clickhouse-grpc-client/src/test/java/com/clickhouse/client/grpc/ClickHouseGrpcClientTest.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpClient.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
clickhouse-http-client/src/main/java11/com/clickhouse/client/http/HttpClientConnectionImpl.java
clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpConnectionTest.java
clickhouse-http-client/src/test/java/com/clickhouse/client/http/DefaultHttpConnectionTest.java
clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/connection/ClickHouseConnection.java
clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/connection/ClickHouseConnectionMetadata.java
examples/client/src/main/java/com/clickhouse/examples/jdbc/Main.java

* remove deprecated API load, dump, and connect
* remove use_no_proxy settings

Remove deprecated api settings

---

CHANGELOG.md
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataConfig.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java

Change default HTTP Client to Apache HTTP Client 
set automatically snd/rcv socket buffer 

Change default http client to apache http client

---

clickhouse-http-client/pom.xml

The new default HTTP library (Apache HTTP) requires a slf4j dependency. Failing to provide this dependency will result in exceptions, leading the system to fall back to an alternative HTTP library.

including back slf4j api for apache http

---

clickhouse-data/src/main/java/com/clickhouse/data/stream/BlockingPipedOutputStream.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/HttpUrlConnectionImpl.java
clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpClientTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/JdbcIssuesTest.java

Fix buffering issue caused by decompress flag not to work

---

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/InputBasedPreparedStatement.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/JdbcIssuesTest.java

Will close Issue #1373 
Fix the case while we have an error in addBatch method 

Closing Issue #1373

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNodes.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseNodesTest.java
clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpClientTest.java

Fixes two bugs in how `ClickHouseNodes.check()` detects faulty nodes:
1. `ClickHouseNodes.check()` uses `ClickHouseClient.ping` to figure out if a node is up and running. The `ping` method uses `ClickHouseClient.read(ClickHouseNode)`. Before this fix it wasn't always querying the specified node, but could query any available nodes.
2. Healthy nodes weren't marked as faulty because of an incorrect condition.
Fixes https://github.com/ClickHouse/clickhouse-java/issues/1502.

Fix faulty node detection in ClickHouseNodes

---

clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataType.java

Fix issue in: https://github.com/ClickHouse/clickhouse-java/issues/1505 by making string type case-insensitive.
Another approach to fix the issue is from Spark's side: https://github.com/apache/spark/pull/44459. 
- Changes are verified using a local setup

Fix integration with Spark for array string type

---

clickhouse-data/src/main/java/com/clickhouse/data/format/BinaryDataProcessor.java
clickhouse-data/src/main/java/com/clickhouse/data/format/BinaryStreamUtils.java
clickhouse-data/src/test/java/com/clickhouse/data/format/BinaryStreamUtilsTest.java

- Update Date32 and DateTime64 range for ClickHouse [#1103](https://github.com/ClickHouse/clickhouse-java/issues/1103)
- Remove datetime64 limits check layer as was done in [#1386](https://github.com/ClickHouse/clickhouse-java/pull/1386)

Update Date32 and DateTime64 range for ClickHouse, remove datetime64 limits check layer

---

CHANGELOG.md
README.md
clickhouse-grpc-client/pom.xml
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcChannelFactory.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcClient.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcClientImpl.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcResponse.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseStreamObserver.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/FramedLZ4Utils.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/NettyChannelFactoryImpl.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/OkHttpChannelFactoryImpl.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/config/ClickHouseGrpcOption.java
clickhouse-grpc-client/src/test/java/com/clickhouse/client/grpc/ClickHouseGrpcChannelFactoryTest.java
clickhouse-grpc-client/src/test/java/com/clickhouse/client/grpc/ClickHouseGrpcClientTest.java

Deprecation of ClickHouse GRPC Client

Deprecation of ClickHouse GRPC Client

---

clickhouse-client/src/test/resources/containers/clickhouse-server/config.d/custom_config.xml

Addreses #1532
Disable ipv6 mode for keeper-server for testcontainers environment because otherwise ClickHouse does not start in docker and integration tests are failed to run

Disable ipv6 mode for keeper-server for testcontainers environment.

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseException.java
clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java

There is a fix in CH > 24.2 that does check for columns marked as `LowCardinality` in nested types (Array/Tuple/Map). 
See https://github.com/ClickHouse/ClickHouse/pull/59385  
- [X ] Unit and integration tests covering the common scenarios were added

Fix integration tests against LATEST to address suspicious low cardinality array check.

---

CHANGELOG.md
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java

Add error code extraction if errorMsg is empty.

Add error code extraction if errorMsg is empty.

---

clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpClient.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpClientTest.java
clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpConnectionTest.java

- Add client address to http referer by default
Send a request to ClickHouse with default settings and We will get client address in ClickHouse `system.query_log`
```
Row 1:
──────
query:           select * from system.numbers limit 53
client_hostname:
client_name:
http_referer:    10.211.42.53
http_user_agent: ClickHouse-JdbcDriver/0.6.0-SNAPSHOT (Linux/5.4.0-53-generic; OpenJDK 64-Bit Server VM/17.0.10+7-Ubuntu-120.04.1; HttpURLConnection; rv:be06439)
```

Add client address to http referer by default

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseException.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseExceptionTest.java

Using a more elegant Pattern-Matcher method to extract error code from error message.
Remove and avoid from hard coding of "Poco::Exceptions" and similar format.

Using a more elegant Pattern-Matcher method to extract error code from error message

---

CONTRIBUTING.md

Fix bad TestNG URL in the [CHANGELOG.md](https://github.com/ClickHouse/clickhouse-java/blob/main/CHANGELOG.md) guide
Nothing relevant enough to be added to [CHANGELOG.md](https://github.com/ClickHouse/clickhouse-java/blob/main/CHANGELOG.md)

Fix TestNG URL

---

CHANGELOG.md
clickhouse-cli-client/src/test/java/com/clickhouse/client/cli/ClickHouseCommandLineClientTest.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseException.java
clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
clickhouse-grpc-client/src/test/java/com/clickhouse/client/grpc/ClickHouseGrpcClientTest.java

Fix for issue #1470 
Connect time out errors are not detected correctly for Apache HTTP client because error message  for this client is in different format e.g: 
```
Connect to http://192.168.2.122:8123/ [/192.168.2.122] failed: connect timed out
```
As a result errors like
```
Caused by: com.clickhouse.client.internal.apache.hc.client5.http.ConnectTimeoutException: Connect to http://192.168.2.122:8123/ [/192.168.2.122] failed: connect timed out
```
are not detected as eligible errors to execute failover.
`ClickHouseException.isConnectTimedOut` is changed to detect `connect timed out` substring in any part of error message

Fix failover for Apache HTTP client. Connect timeout error is not detected correctly

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseConfigTest.java
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataConfig.java

Max buffer size can now be overridden by user 

Fixed max buffer limitation

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseResponseSummary.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseResponseSummaryTest.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcResponse.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseStreamObserver.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpResponse.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/OperationStatistics.java
client-v2/src/main/java/com/clickhouse/client/api/insert/InsertResponse.java
client-v2/src/main/java/com/clickhouse/client/api/internal/StopWatch.java
client-v2/src/main/java/com/clickhouse/client/api/query/QueryResponse.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Adds class to represent metrics of an operation. 

Operation (Query) Metrics 

---

CHANGELOG.md
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpClient.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/AccessManagementTest.java

Reset roles by "SET ROLE NONE"

---

clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseDoubleValue.java
clickhouse-data/src/test/java/com/clickhouse/data/format/ClickHouseTabSeparatedProcessorTest.java

When SQL is formatted using the `FORMAT TabSeparatedWithNamesAndTypes` in ClickHouse
the `ClickHouseTabSeparatedProcessor` will `update` the value as a `String`. In this case, if the double type is `inf, -inf, or nan`, it will not be able to be parsed.
for example

DoubleValue update of inf str

---

clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/ClickHouseResult.java
clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/ClickHouseResult091.java

Mono resource manager for updateCount close the response when complete

fix response close for getRowsUpdated(#1538)

---

clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/ClickHouseResult.java
clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/ClickHouseResult091.java

Reverts ClickHouse/clickhouse-java#1539
Fails the  com.clickhouse.r2dbc.spi.test.R2DBCTestKitImplTest.segmentSelectWithEmitsRow what is part of a 3rd party test kit

Revert "fix response close for getRowsUpdated(#1538)"

---

.github/workflows/build.yml
clickhouse-r2dbc/pom.xml
client-v2/pom.xml
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
pom.xml

- Local test runs consume a lot of time. We need to optimize it 
- CI log is full of test output that is needed only when failed. 
- Test output is redirected to a file so will be available on failure as downloadable artifact
- If test failed its stacktrace is shown

Improvements to speedup tests and make logs more readable in Actions

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/internal/ClientV1AdaptorHelper.java

Proxy configuration is copied to client used by operations. 

[client-v2] Fix proxy configuration globally for the client

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNode.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/internal/ClientV1AdaptorHelper.java
client-v2/src/test/java/com/clickhouse/client/ClientTests.java

Because not every property is passed to the config of underlying client, it was not possible to connect over SSL.

[client-v2] fixed passing properties to old client

---

CHANGELOG.md
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHousePreparedStatement.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java

This is an attempt to reanimate #1434 to enable `getMetadata()` method to return metadata for a prepared `SELECT` query that hasn't yet been executed. Also see #1430 .
This functionality is needed (among other use-cases) to support [query passthrough](https://github.com/trinodb/trino/pull/12325) for [clickhouse-connector](https://trino.io/docs/current/connector/clickhouse.html) inside [Trino](https://trino.io/).
`DESCRIBE (<select>)` is used to retrieve metadata about `SELECT` query that hasn't yet been executed. 
Contrary to #1434 the method requires the query to be "recognized" and be `SELECT`, thus removing the ambiguity of supporting different query types. Otherwise it wraps the query inside `DESCRIBE ()` clause to build respective metadata object.
Additional unit tests were added to …

[clickhouse-jdbc] describe SELECT queries to retrieve metadata

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/command/CommandResponse.java
client-v2/src/main/java/com/clickhouse/client/api/command/CommandSettings.java
client-v2/src/test/java/com/clickhouse/client/command/CommandTests.java

Closes https://github.com/ClickHouse/clickhouse-java/issues/1690 

[client-v2] Added executCommand API

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
clickhouse-http-client/src/test/java/com/clickhouse/client/http/ApacheHttpConnectionImplTest.java

Apache HC has a great feature of checking for stale connection. Once this feature has been added to the our client but disappeared after some time due to refactoring (unfortunately it happens). 
Here is original PR https://github.com/ClickHouse/clickhouse-java/pull/760
New http client option is added to the `com.clickhouse.client.http.config.ClickHouseHttpOption`
```java 
/**
* The time in milliseconds after which the connection is validated after inactivity.
* Default value is 5000 ms. If set to negative value, the connection is never validated.
* It is used only for Apache Http Client connection provider.
*/
AHC_VALIDATE_AFTER_INACTIVITY("ahc_validate_after_inactivity", 5000L,
"The time in milliseconds after which the connection is validated after inactivity."),
```
Delete items not …

added settings for AHC to validate when stale

---

clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseRequestTest.java
clickhouse-http-client/src/main/java11/com/clickhouse/client/http/HttpClientConnectionImpl.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java

In the JDBC driver every Statement has own request object, but it is shared among requests. If statement object is used by different threads then one thread may copy query_id set by another. Ignoring the fact that threads should not share Statements there should be a proper synchronization when working with shared request object. 
Current PR implements locking on request object while making copy (seal operation). 
Closes: 
- https://github.com/ClickHouse/clickhouse-java/issues/1529

Fix duplicate query ID error 

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpClient.java

This a possible fix for #1729.
As far as I can tell link-local addresses are useless for the purpose of `getLocalhost` since it's used to get a referrer address, so I ignored them.
This solves my issue on my macOS system: for all others addresses the `getCanonicalHostName` is almost instantaneous.
Additionally, the comment says "use the first non-loopback address" but the code didn't actually do that because the break doesn't apply to the outer loop, I fixed that too.

clickhouse-http-client: ignore link local addresses in getLocalhost

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/NativeFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesAndTypesFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/query/QueryResponse.java
client-v2/src/main/java/com/clickhouse/client/api/query/QuerySettings.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Previous implementation was using ClickHouseInputStream and BinaryStreamUtils to read data. 
This PR removes any references for this two classes from client v2 code 
Bonus: 
There is a fix for premature summary. Operations like `queryAll` or `queryRecords` require to have result rows count. However summery doesn't guarantee to have it correct if no `wait_end_of_query=true` is set.

[client-v2] Migrate to use InputStream do read data

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/ClientMisconfigurationException.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/main/java/com/clickhouse/client/api/internal/MapUtils.java
client-v2/src/test/java/com/clickhouse/client/ProxyTests.java

- Added forwarding proxy configuration to new http layer 
- Added auth configuration for proxy
- Added ability to disable storing cookies

[client-v2] Proxy support

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/NativeFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesAndTypesFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/query/Records.java
client-v2/src/test/java/com/clickhouse/client/ClientTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Some streams return `0` when `available()` called even when data is available. Some streams may throw EOFException while read some may not. So only check for number of read bytes or result of `read()` really works. 
If we want to wrap a stream of data into collection we must properly implement `hasNext()`. Because of problem#1 we can not do it easily
- Check `read()` result and throw EOFException 
- Read data up-front. It will give some overhead, but it is simplest solution 
- Logic is based on EOFException what is bad, but can be fixed in future with passing error handler to each read or returning tuples (what will be a memory overhead) 
- If EOFException is throw before reading next record - it assumes that if we at the start of row reaching end of stream indicates that no row is sent …

[client-v2] Fix reading binary streams

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/insert/InsertResponse.java
client-v2/src/main/java/com/clickhouse/client/api/query/QueryResponse.java
client-v2/src/test/java/com/clickhouse/client/ClientTests.java

Previously old client was instantiated for each operation in the new client version. It lead to performance degradation and memory overhead. 
Current PR instantiates old client and make it reusable by all operations

[client-v2] made old client instantiated on new client creation

---

client-v2/pom.xml
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/internal/ClickHouseLZ4InputStream.java
client-v2/src/main/java/com/clickhouse/client/api/internal/ClickHouseLZ4OutputStream.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/main/java/com/clickhouse/client/api/internal/LZ4Entity.java
client-v2/src/main/java/com/clickhouse/client/api/internal/MapUtils.java
client-v2/src/main/java/com/clickhouse/client/api/internal/TableSchemaParser.java
client-v2/src/test/java/com/clickhouse/client/ClientTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertClientContentCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertClientHttpCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryServerContentCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryServerHttpCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Implements support for next compression scenarios:
- whole http response from a server is compressed with LZ4
- enabled when server &  http compression is enabled 
- response body from a server is compressed with LZ4
- http request is compressed with LZ4 
- request body is compressed with LZ4  
Closes https://github.com/ClickHouse/clickhouse-java/issues/1717

[client-v2] Compression Support

---

clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/ClickHouseCommandLineResponse.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseResponse.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseSimpleResponse.java
clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseStreamResponse.java
clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcResponse.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpClient.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpResponse.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesAndTypesFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/internal/MapUtils.java
client-v2/src/main/java/com/clickhouse/client/api/internal/SettingsConverter.java
client-v2/src/main/java/com/clickhouse/client/api/query/QueryResponse.java
client-v2/src/main/java/com/clickhouse/client/api/query/QuerySettings.java
client-v2/src/main/java/com/clickhouse/client/api/query/Records.java
client-v2/src/test/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReaderTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/SimpleReader.java

There are two options for the timezone for parsing DateTime values:
- use server timezone (pre-fetch or header) 
- use user specified timezone 
This PR implement these options when old or new implementation are used. 

[client-v2] Attach TimeZone to a QueryResponse & use TimeZone settings in binary readers

---

client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/test/java/com/clickhouse/client/ConnectionManagementTests.java

Fixes configuration parameter for connection reuse strategy

[client-v2] Connection reuse strategy parameter

---

.github/workflows/nightly.yml
.github/workflows/release.yml
CHANGELOG.md
clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
examples/client-v2/pom.xml
examples/client/pom.xml
examples/demo-service/build.gradle.kts
examples/jdbc/pom.xml
pom.xml

- Version updates 
- Changelog updated

Pre 0.6.4 Updates 

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java

Possible fix for https://github.com/ClickHouse/clickhouse-java/issues/1780
As I understand it, this field will not be null if you have explicitly specified time zone in the database.
To fix this, i just repeated the code that was above, because I don’t think that the functionality in the JVM can depend on the bit depth of DateTime
Maybe it's just a typo?
Closes https://github.com/ClickHouse/clickhouse-java/issues/1780

[client-v2] Fix: null TimeZone Exception

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/BigDatasetExamples.java
examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/data/NumbersRecord.java

Adds a property to configure a buffer that is used to read data from a socket

[client-v2] Add property for network buffer size

---

client-v2/src/main/java/com/clickhouse/client/api/internal/ClickHouseLZ4InputStream.java
client-v2/src/test/java/com/clickhouse/client/query/QueryServerContentCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
examples/demo-service/src/main/java/com/clickhouse/demo_service/DbConfiguration.java

`com.clickhouse.client.api.internal.ClickHouseLZ4InputStream` had an optimization - header buffer, but it was static and shared thru all instances. This PR fixes this. 

[client-v2] Fix compression issue when concurrent requests

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/NativeFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryReaderBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/query/GenericRecord.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

improved queryAll() to use less mem

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/metadata/TableSchema.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

- Fixes getting arrays as list 
- Removes need to use iterator for reading thru columns 
- Fix reading Ipv4 addresses

[client-v2] Fix reading arrays

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
examples/demo-service/src/main/java/com/clickhouse/demo_service/DbConfiguration.java

Internally data is read into a map that represents a record. `clear()` was called each time before reading data to protect from stale data from a previous records. However it is not needed because it is always same number of columns are read. Only case with null should be handled correctly to clean up non-null values.
This single change reduces number of Map$Node object by magnitude. 

[client-v2] Fixed reusing map without creating new nodes

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java

Currently, connection TTL & queue strategy are logged at INFO level for every request. This can result in a lot of noise in logs:
This PR switches them to DEBUG log levels.

Use debug logging for internal connection details

---

clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/connection/ClickHouseConnectionFactory.java

https://github.com/ClickHouse/clickhouse-java/issues/1447
Defer connection creation, in order to be able to use R2DBC pool. This allows pool to create a new instance on every subscription, instead of always returning the same one. 
The linked issue explained the problem very well.

R2DBC - Defer connection creation

---

.github/workflows/analysis.yml
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/NativeFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesAndTypesFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/internal/BasicObjectsPool.java
client-v2/src/main/java/com/clickhouse/client/api/internal/CachingObjectsSupplier.java
client-v2/src/main/java/com/clickhouse/client/api/query/Records.java
client-v2/src/test/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReaderTests.java
client-v2/src/test/java/com/clickhouse/client/query/BinaryReadyReusesBuffersTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
client-v2/src/test/java/com/clickhouse/client/query/UsingPreallocatefReadBuffers.java
examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/BigDatasetExamples.java
examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/SimpleReader.java
examples/demo-service/src/main/java/com/clickhouse/demo_service/DatasetController.java

A lot small buffers may be allocated while reading numeric information. 
This PR implements a reusing buffers withing a reader. It is not a default behavior. 
Introduced `Client.Builder#allowBinaryReaderToReuseBuffers` to control the behavior 
Note: 
- implementation is not thread-safe 
- reader should be called by one thread at a time
- small buffers will 64 bytes are pre-allocated 

[client-v2] reader buffer optimization

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/insert/InsertSettings.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/main/java/com/clickhouse/client/api/internal/LZ4Entity.java
client-v2/src/main/java/com/clickhouse/client/api/internal/SerializerUtils.java
client-v2/src/main/java/com/clickhouse/client/api/internal/TableSchemaParser.java
client-v2/src/main/java/com/clickhouse/client/api/metadata/TableSchema.java
client-v2/src/test/java/com/clickhouse/client/ClientTests.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertClientContentCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertClientHttpCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
client-v2/src/test/java/com/clickhouse/client/insert/SamplePOJO.java
client-v2/src/test/java/com/clickhouse/client/query/QueryServerContentCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryServerHttpCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
examples/demo-service/src/main/java/com/clickhouse/demo_service/DatasetController.java

- Added more data type tests 
- Fixed read error from response 
- Added possibility to register class against different tables. 

[client-v2] Tests and Fixes in scope of SerDe

---

clickhouse-jdbc/pom.xml
examples/demo-kotlin-service/build.gradle.kts

Dependencies to `clickhouse-data` and `clickhouse-client` project were broken while removing dependencies for grpc and cli client from JDBC artifact. 
Current PR restores required dependencies. Previously `all` artifact had different dependencies than `shaded`. 
Closes https://github.com/ClickHouse/clickhouse-java/issues/1823

[jdbc] Restores jdbc-all.jar  content

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java

This PR makes sure that ClientStats for operation is always present and do not cause NPE. 
Closes https://github.com/ClickHouse/clickhouse-java/issues/1839

[client-v2] Fix for case when operation metrics not found

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/query/Records.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

BinaryFormatReader implementation is stateful and hold current record to be accessible before calling `next()`. Data is provided as stream and because of this reason handling `hasNext()` is complex because reader should read data upfront without affect current own position to avoid skipping records. 
This PR fixes detecting if no data is present in data stream. 
**Note**
There are two cases of empty result:
- `SELECT 1 LIMIT 0` - has no result data but has column name and type
- `CREATE TABLE test` - has nothing at all, so readers that expect schema before data should also handle it correctly. 
Closes https://github.com/ClickHouse/clickhouse-java/issues/1788

[client-v2] Fixes handling empty results while using reader

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNodes.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseNodeTest.java
clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseNodesTest.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
clickhouse-jdbc/pom.xml
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDriverTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/internal/ClickHouseJdbcUrlParserTest.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/ClientSettings.java
client-v2/src/main/java/com/clickhouse/client/api/insert/InsertSettings.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/main/java/com/clickhouse/client/api/query/QuerySettings.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
examples/demo-kotlin-service/build.gradle.kts

Adds two new configuration options for client and operations:
- `httpHeader` - to set additional http headers or override already set one's 
- `serverSetting` - to pass settings to a server (thru query parameters in case of HTTP) 
Closes https://github.com/ClickHouse/clickhouse-java/issues/1782
Closes https://github.com/ClickHouse/clickhouse-java/issues/1750
Closes https://github.com/ClickHouse/clickhouse-java/issues/1665

[client-v2] Added options for additional headers and server settings

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/internal/SerializerUtils.java
client-v2/src/main/java/com/clickhouse/client/api/query/POJOSetter.java
client-v2/src/test/java/com/clickhouse/client/internal/SerializerUtilsTests.java
client-v2/src/test/java/com/clickhouse/client/query/QuerySamplePOJO.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Current implementation reads all values into objects even it can be done using primitive types. It was done to simplify code, but it may be not good for memory consumption.
Current PR:
- adds methods to read values into primitives 
- updates POJO deserialization code to use these new methods

[client-v2] primitive reading into pojo

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java

Removed logging of end of stream - because too confusing and verbose.

[client-v2] remove info log for end of stream

---

client-v2/src/main/java/com/clickhouse/client/api/DataTypeUtils.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Added more tests for DateTime values and made it be read with column defined scale.
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1851

[client-v2] Fixes BinaryStreamReader parsing DateTime64 values. Using a column defined scale now. 

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/internal/SerializerUtils.java
client-v2/src/test/java/com/clickhouse/client/insert/SamplePOJO.java

When using the client-v2 with nullable nested columns, client-v2 was unable to insert them as it was treating the inner items as non nullable. Have not tested it but I guess that the same thing was happening for Array(Nullable(column_type)).
These changes aim to check whether array base column is nullable and if the item in the array is also null, serialize null.
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1858
- [x ] Unit and integration tests covering the common scenarios were added

[client-v2] Nullable nested column

---

client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java

A HTTP requests to clickhouse which ended with server error (>500)  throw a `ServerException`.
Closes: #1874

[client-v2] Fix handling HTTP error status codes

---

clickhouse-http-client/pom.xml
clickhouse-jdbc/pom.xml
client-v2/pom.xml
examples/client-v2/pom.xml
examples/demo-kotlin-service/build.gradle.kts
examples/demo-service/build.gradle.kts
examples/demo-service/src/main/java/com/clickhouse/demo_service/DbConfiguration.java
pom.xml

Client uses compression by default, but related library dependencies are optional. It causes confusion because users have to add extra dependencies while library cannot work without it without adjustments. 
This PR fixes:
- compression dependencies are required.
- apache http client dependencies are cleaned  up 
- updated in examples 
Currently dependencies look like: 
```
productionRuntimeClasspath
+--- com.clickhouse:client-v2:0.7.0-SNAPSHOT
|    +--- com.clickhouse:clickhouse-client:0.7.0-SNAPSHOT
|    +--- com.clickhouse:clickhouse-data:0.7.0-SNAPSHOT
|    +--- org.slf4j:slf4j-api:2.0.7 -> 2.0.13
|    +--- org.apache.httpcomponents.client5:httpclient5:5.3.1
|    +--- org.lz4:lz4-pure-java:1.8.0
|    +--- org.apache.commons:commons-compress:1.27.1
|    +--- …
```

[client-v2] Make compression dependencies as required

---

README.md

Provide links to Javadoc reference documentation using the hosted Javadoc at https://javadoc.io/.

docs: add Javadoc links for ClickHouse Java clients

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
client-v2/src/test/java/com/clickhouse/client/command/CommandTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Fixes the problem with case when server responds "200 OK" but then long running query fails and headers have exception code. 
Linked to https://github.com/ClickHouse/clickhouse-java/issues/1821 

[client-v2] Fixes handling error when successful http status by error code header in response

---

client-v2/src/main/java/com/clickhouse/client/api/internal/SettingsConverter.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java

Closes: https://github.com/ClickHouse/clickhouse-java/issues/1821

Error handling tests

---

clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java

This commit solves the issue #1827 by logging the exception instead of printing it to stdout. A log in the client v2 has also been added so that both clients are iso.

Fix JDBC driver prints stack trace to stdout

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpProto.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/ClientSettings.java
client-v2/src/main/java/com/clickhouse/client/api/command/CommandResponse.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/insert/InsertSettings.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/main/java/com/clickhouse/client/api/query/QuerySettings.java
client-v2/src/test/java/com/clickhouse/client/SettingsTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

There is a [feature](https://clickhouse.com/docs/en/interfaces/http#setting-role-with-query-parameters) and it should be supported by the new client. It allows to set roles for every operation where session may not be maintained (http requests are balanced between different DB instances). 
!! Documentation should be updated also. 
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1832

[client-v2] Added session roles for client and operations

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDriver.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java

Many users use Apache Spark (or any other framework) via this JDBC connector.
This PR adds "framework detecting" functionality. It looks at the current stack trace, infers the framework usage based on a closed list of tracked frameworks, and adds an indication for it in the user agent string.

[jdbc] Enhance useragent to indicate Apache Spark

---

clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpProto.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/AccessManagementTest.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/ClientSettings.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java

Password can be passed as value of the `X-ClickHouse-Key` header [docs](https://clickhouse.com/docs/en/interfaces/http#default-database). But header values have some limitations about what characters can be used (learned from practical tests and https://www.rfc-editor.org/rfc/rfc7230#section-3.2.6) what would require escaping special chars. Basic authentication helps to avoid all this and is standard authentication mechanism.
This PR changes both clients (v1, v2). 
New configuration parameter is added: 
- `com.clickhouse.client.http.config.ClickHouseHttpOption#USE_BASIC_AUTHENTICATION` - allows to switch using ClickHouse `X-` headers to authenticate. Default is using basic auth. 
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1305

[client-v1,client-v2, auth] Implemented authentication via http basic auth

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/SerializerUtils.java
client-v2/src/test/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReaderTest.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Number values can be converted to boolean and visa versa. This PR fixes this and adds proper conversion boolean to numbers.
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1908

[client-v2] Implements conversion from boolean, to boolean. Added tests

---

clickhouse-jdbc/pom.xml
examples/jdbc/README.md
examples/jdbc/pom.xml

There is a package classifier "http" with shaded AHC. While deprecation of some components one crucial dependency was removed that (surprise!) was used in base scenario. This PR returns this dependency and adds profiles to example so it can be verified. 
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1912

[JDBC] Added removed dependency to shaded jar. Corrected jdbc example to verify

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/SerializerUtils.java
client-v2/src/main/java/com/clickhouse/client/api/query/GenericRecord.java
client-v2/src/test/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReaderTest.java
client-v2/src/test/java/com/clickhouse/client/internal/SmallTests.java

Closes: https://github.com/ClickHouse/clickhouse-java/issues/1954

[client-v2] removed float/double overflow check

---

clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java

This PR fixes two problems: 
- force value for `result_overflow_mode` that was set to `break` and it was not possible to override it. Enforced in JDBC and in HTTP connection
- correct handling of `max_result_rows` - in attempt to make it 0 this setting was removed from request settings and because of this was set to client setting value what is wrong. It happens in ClickHouseHttpConnection. 
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1932

Fixed overriding max_result_rows settings

---

client-v2/docs/dependencies.md
client-v2/pom.xml
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java
client-v2/src/main/java/com/clickhouse/client/api/ClientSettings.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/http/ClickHouseHttpProto.java
client-v2/src/main/java/com/clickhouse/client/api/insert/InsertResponse.java
client-v2/src/main/java/com/clickhouse/client/api/insert/InsertSettings.java
client-v2/src/main/java/com/clickhouse/client/api/internal/ClientV1AdaptorHelper.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/main/java/com/clickhouse/client/api/internal/ServerSettings.java
client-v2/src/main/java/com/clickhouse/client/api/internal/SettingsConverter.java
client-v2/src/main/java/com/clickhouse/client/api/internal/TableSchemaParser.java
client-v2/src/main/java/com/clickhouse/client/api/metrics/OperationMetrics.java
client-v2/src/main/java/com/clickhouse/client/api/query/QueryResponse.java
client-v2/src/main/java/com/clickhouse/client/api/query/QuerySettings.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
client-v2/src/test/java/com/clickhouse/client/ProxyTests.java
client-v2/src/test/java/com/clickhouse/client/SettingsTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
client-v2/src/test/java/com/clickhouse/client/metadata/MetadataTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/ExperimentalJSONExample.java
pom.xml

Client-v2 still uses some classes from old client. This PR fixes this. 
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1899

[client-v2] Remove dependencies on old projects 

---

client-v2/src/main/java/com/clickhouse/client/api/metrics/OperationMetrics.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Added javadoc for `com.clickhouse.client.api.metrics.OperationMetrics#operationComplete` to warn about side effect if called multiple times.
See: https://github.com/ClickHouse/clickhouse-java/issues/1900

[client-v2] Added documentation for OperationMetrics#completeOperation().

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/NumberConverter.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/SerializerUtils.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Closes: https://github.com/ClickHouse/clickhouse-java/issues/1959

[client-v2] Add ability to pass query parameter to queryAll and queryRecords methods. 

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/NativeFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryReaderBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/query/GenericRecord.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Closes: https://github.com/ClickHouse/clickhouse-java/issues/1990

[client-v2] Fix reading Array(Uint64)

---

jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/JdbcConfigurationTest.java

Fixed the test so:
- only explicit `https` is valid 
- no `ssl` property should require - user should specify secure protocol (may be we need to make it by default https) 

[jdbc-v2] Fixed tests

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/internal/ClickHouseLZ4OutputStream.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertClientContentCompressionTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java

If `ClickHouseLZ4OutputStream#flush()` is called when input buffer  is empty (no data to compress) then `ClickHouseLZ4OutputStream` will create an empty frame that will cause error on server side like: 
`Can't decompress data: header is corrupt with decompressed block size 0: While executing ParallelParsingBlockInputFormat. (CANNOT_DECOMPRESS)` 
Linked to: https://github.com/ClickHouse/clickhouse-java/issues/1993

[client-v2] Fix ClickHouseLZ4OutputStream sending extra bytes when income buffer is empty 

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/DriverProperties.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/metadata/DatabaseMetaData.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/JdbcIntegrationTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/metadata/DatabaseMetaDataTest.java

Some application want to ignore JDBC standard behavior. This PR adopts JDBC driver for such needs:
- schema term is configurable now. Default is `schema` in the meaning that schema is used over catalog.
- added property to control if `SQLFeatureNotSupportedException` should be thrown
- DatabaseMetaData#getColumns() returns full column data-type (with `Nullable`) 

[jdbc-v2] Adopt for non-compliant requests

---

CHANGELOG.md
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java

The [catch block accepts `ConnectTimeoutException`](https://github.com/ClickHouse/clickhouse-java/blob/02542cc5b7a2f9ad09a816afd25308ea7da57519/client-v2/src/main/java/com/clickhouse/client/api/Client.java#L1411); however, `shouldRetry` checks for `ConnectException`.
I think the solution is for `shouldRetry` to test for `ConnectTimeoutException`, please let me know if that's incorrect so that i can adjust the `catch` clause instead.
It's also worth noting that `wrapException` tests for `ConnectException`; however, `wrapException` will never only ever be called with `NoHttpResponseException | ConnectionRequestTimeoutException | ConnectTimeoutException`, which makes me wonder if:
- `ConnectException` there should be replaced with `NoHttpResponseException`
- _or_ `ConnectException` should be …

[client-v2] Fix check for ConnectTimeoutException in shouldRetry

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/NativeFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/metadata/TableSchema.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/ResultSetImpl.java

- implements `com.clickhouse.client.api.metadata.TableSchema#columnIndexToName` to get column by natural index 
- fixes all places where old `com.clickhouse.client.api.metadata.TableSchema#indexToName` is used. 

[client-v2] fixed calculating index in getters

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java

Set wait-end-of-query to 0 in jdbc-v2 init i have left it on 0 in case clickhouse server will change the default 

Set wait-end-of-query to 0 in jdbc-v2 init

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java

Table name was wrongly wrapped with `\"`. This should be up to user. 

[client-v2] Fix table name wrapping in insert statement

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/ResultSetImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java

Tableau fix getDate with calendar

Tableau fix getDate with calendar

---

.github/workflows/stale.yml

follow-up on https://github.com/ClickHouse/clickhouse-java/pull/2037
Settings:
- mark an issue as stale after a year of inactivity, close in 30 days
- mark a PR as stale after a month of inactivity, close in 14 days

enable stalebot

---

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDriver.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/AccessManagementTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseConnectionTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDataSourceTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDriverTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseResultSetTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/CombinedResultSetTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/GenericJDBCTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/JdbcIssuesTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/JdbcParameterizedQueryTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/JdbcParseHandlerTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImplTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/internal/ClickHouseJdbcUrlParserTest.java
clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/internal/JdbcTransactionTest.java

Set JDBC v2 as default driver 

Set JDBC v2 as default driver 

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/test/java/com/clickhouse/client/ClientTests.java

Do not close provided executor on `Client#close()`

[client-v2] Do not close provided executor

---

client-v2/pom.xml
client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/main/resources/client-v2-version.properties
examples/client-v2/pom.xml
pom.xml

Version of the package can be hardcoded in a resource file or java one and version can be get from MANIFEST.MF. 
The last one is not required and may miss some records. Implementations relying on `getClass().getPackage().getImplementationVersion()` is unstable and in most cases it may return null or malformed information.
This PR make this approach only for dynamic version detection of 3rd-party libraries. Otherwise versions are read from resource file that is filed on building stage and guarantee to be present. 

added manifest properties. fixed getting http client version

---

.github/workflows/nightly.yml
.github/workflows/release.yml
CHANGELOG.md
examples/client-v2/pom.xml
examples/client/pom.xml
examples/demo-kotlin-service/gradle.properties
examples/demo-service/gradle.properties
examples/jdbc/pom.xml
examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/DriverTest.java
pom.xml

- Updates version to new release 
- Updates change log with all changes 

Updated version for the new release

---

clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseUtils.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseUtilsTest.java

Throws an exception when try to find a file with reserved character in the file path on Windows OS
[Test failure in Windows when attempting to locate files with reserved characters in the file path.](https://github.com/ClickHouse/clickhouse-java/issues/2114)
Closes [Test failure in Windows when attempting to locate files with reserved characters in the file path.](https://github.com/ClickHouse/clickhouse-java/issues/2114)

PR Fixes failing Test in Windows when attempting to locate files with reserved characters in the file path

---

client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
client-v2/src/test/java/com/clickhouse/client/metrics/MetricsTest.java

Expired connections are not removed from the pool. It causes two problem with metrics: they do not reflect actual state. 
This PR calls `poolControl.closeExpired()` before each request. It should not create a problem with pool. 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2123

[client-v2] Fixed cleaning expired connections from the pool

---

clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseUtils.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryFormatSerializer.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryReaderBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/SerializerUtils.java
client-v2/src/main/java/com/clickhouse/client/api/query/GenericRecord.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
client-v2/src/test/java/com/clickhouse/client/insert/SamplePOJO.java

Use cases:
```java
public record MyData (OffsetDateTime ts1, Instant ts2) {
}
client.insert(List.of(new MyData(OffsetDateTime.now(), Instant.now())));
```

SerializerUtils support OffsetDateTime and Instant

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
client-v2/src/test/java/com/clickhouse/client/metadata/MetadataTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Passes database in operation settings when doing describe request for a table in non-default DB. 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2139

fixed getTableSchema by passing database to settings

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java

The issue seemed to be in the `parseStatementType` function. I have also added several tests related to this scenario.
Closes #2132 
I'm not sure what to do regarding the changelog. If there's any action required, please guide me. Thank you for your help!

fix: #2132 fix executing queries with 'WITH' clause in jdbc v2

---

clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java

Test creates db with engine `Atomic`. It is not necessary and disabled on cloud instances. 

[jdbc-v2] fixed switching db test

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/SerializerUtils.java
client-v2/src/test/java/com/clickhouse/client/insert/SamplePOJO.java

* Send null when we have null primitives and a nullable column
Closes https://github.com/ClickHouse/clickhouse-java/issues/2122

Send null when nullable

---

clickhouse-jdbc/pom.xml
clickhouse-jdbc/src/test/perf/README.md
clickhouse-jdbc/src/test/perf/com/clickhouse/jdbc/perf/JDBCBenchmarkBase.java
clickhouse-jdbc/src/test/perf/com/clickhouse/jdbc/perf/JDBCBenchmarkRunner.java
clickhouse-jdbc/src/test/perf/com/clickhouse/jdbc/perf/JDBCInsertBenchmark.java
clickhouse-jdbc/src/test/perf/com/clickhouse/jdbc/perf/JDBCSelectBenchmark.java
client-v2/src/test/perf/com/clickhouse/client/ClientBenchmark.java

Performing JDBC testing with JMH 
Closes #2179

JDBC perf test with JMH

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java

In a Spring Boot application using `org.springframework.jdbc.core.JdbcTemplate#queryForList(java.lang.String)`, doing a simple `SELECT * from table` from a table containing `Enum` columns returns the enum values as strings as interpreted by `Object.toString()`. These strings are not meaningful to the caller, since they are of the form `"com.clickhouse.client.api.data_formats.internal.BinaryStreamReader$EnumValue@7331ed36"`
`name` feels to me like the obvious choice to represent an enum value as string.

Implement BinaryStreamReader.EnumValue.toString()

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

This is a response to #2127 which is complementary to #2022. I'm however concerned by my solution as it is, it may be contested or refused. The solution proposed here is by adding a specific check for each operation that gets the dataType to check if it's a simpleAggregateFunction, and if it's the case take the nested column datatype. Maybe a modification of the ClickhouseColumn implementation could be cleaner but its scope is above my understanding at this moment. 
Closes #2127

[client-v2] Fix support in ClickHouseBinaryFormatReader for SimpleAggregateValue

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

An an overload of the execute method, to be used like the queryAll with the sql statement and the query params in a Map<String, Object>. 
I didn't add tests for this method as relaying on the query method only. 
Closes #2152 

feat(ClientV2): Add execute(String, Map<String,Object>)

---

performance/src/test/com/clickhouse/benchmark/clients/MixedWorkload.java

Tweak MixedWorkload to add limit to SELECT

---

performance/src/test/com/clickhouse/benchmark/BenchmarkRunner.java
performance/src/test/com/clickhouse/benchmark/clients/BenchmarkBase.java
performance/src/test/com/clickhouse/benchmark/clients/JDBCInsert.java

Small fixes benchmark
- warmup
- JDBC url for cloud 

Small fixes benchmark

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java

Adds support for getting the table schema for a query with params.
Before this PR, there's no good way to get the table schema for a query that has params. The method `getTableSchemaFromQuery(String sql)` takes a SQL query but no params. This PR simply adds a new method to the client: `getTableSchemaFromQuery(String sql, Map<String, Object> params)`

Support getting table schema from a query with params

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java

Fix bug in insert when we have (?, `parseDateTimeBestEffort`(?, ?), ?, 1) some sql methods and not only ? we have removed that. currently we are inserting what was provided by the user, only looking at the values part
Closes 

sql expression/methods was removed incorrectly from values section  

---

CHANGELOG.md
clickhouse-jdbc/pom.xml

Fixes missing LZ4 dependency in shaded because related package was not included in the list 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2275

[jdbc] Fix missing dependency in shaded package

---

clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/metadata/DatabaseMetaDataTest.java

Added simple test.  
I have run it from an external app that imports the dependency. 
```
<dependency>
<groupId>com.clickhouse</groupId>
<artifactId>clickhouse-jdbc</artifactId>
<version>0.8.2</version>
<classifier>shaded-all</classifier>
</dependency>
```
It works 
Adding as a fallback to load from a class's class loader (for example, in DbVisualizer)
Closes #2245 

Adding issue #2245 test

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/JdbcConfigurationTest.java

Solves issue #2206

---

clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java
client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryFormatWriter.java
client-v2/src/main/java/com/clickhouse/client/api/internal/TableSchemaParser.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
client-v2/src/test/java/com/clickhouse/client/insert/SimplePOJO.java

This pull request introduces support for handling default values in ClickHouse columns, including `MATERIALIZED`, `ALIAS`, and `EPHEMERAL` types. It adds new functionality to skip these columns during data insertion and ensures proper parsing and testing of default expressions. The most important changes are grouped below:
* Added a new `DefaultValue` enum to represent different default types (`DEFAULT`, `MATERIALIZED`, `EPHEMERAL`, `ALIAS`) and associated fields `defaultValue` and `defaultExpression` to the `ClickHouseColumn` class.
* Introduced getter and setter methods for `defaultValue` and `defaultExpression` in the `ClickHouseColumn` class.
* Updated the `insert` method in `Client.java` to skip columns with default values other than `DEFAULT` during data insertion.
* Modified the …

Issue 2118

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java

Solve 2327 - Does not escape correctly UUID
Closes #2327

Solve 2327 - Does not escape correctly UUID

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java

StringIndexOutOfBoundsException on empty collection in the encodeObject method.
Closes #2329

Solve issue 2329 - StringIndexOutOfBoundsException on empty collection

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java

If the client wants to disable the retrieval of the server version & server timezone (extra query when init of JDBC Connection)
Example (how to disable)
```
properties.put(ClientConfigProperties.SERVER_TIMEZONE.getKey(), "GMT");
properties.put(ClientConfigProperties.SERVER_VERSION.getKey(), "1.0.0");
```
Closes #2191

Solves issue-2191

---

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/DriverV1.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/Driver.java

To improve our metrics and tracking, we added two more frameworks that can use the JDBC package: [Flink JDBC](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/datastream/jdbc/) and [NIFI JDBC](https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-dbcp-service-nar/1.17.0/org.apache.nifi.dbcp.DBCPConnectionPool/index.html).
This feature was verified for the Flink JDBC connector.

Add Apache Flink and Apache Nifi to frameworks detection

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/test/java/com/clickhouse/client/ClientTests.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java

Fixes #2355 by using default JVM pool in case executor is no specified by client nor client is configured for async operations 

[client-v2] fixed NPE and added test

---

client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java

Test `com.clickhouse.jdbc.DataTypeTests#testDateTypes` had a problem when:
1. Server is in UTC 
2. Client is in another timezone 
This is not reproducible on CI because everything in UTC timezone.

[jdbc-v2] Fixed test to use different from server (UTC) timezone

---

jdbc-v2/pom.xml

There was an error while running Metabase tests: 
```
java.lang.NoClassDefFoundError: Could not initialize class com.clickhouse.jdbc.internal.ClickHouseLexer
java.lang.ExceptionInInitializerError: Exception java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4). [in thread "CLI-agent-send-off-pool-1"]
```
This PR upgrades to the latest version to fix it. 

upgraded version of antlr4

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/InetAddressConverter.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/SerializerUtils.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java

Fixes address conversion when actual value is IPv4 and column is IPv6 
Closes #2342 

[jdbc-v2] Fixes IPv6 address conversion into IPv4

---

client-v2/src/main/java/com/clickhouse/client/api/metadata/TableSchema.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/ResultSetImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/ResultSetImplTest.java

Now `findColumn` returns actual column's index.
Closes https://github.com/ClickHouse/clickhouse-java/issues/2375.
The reason this method returns 0 is the following: this method obtains an instance of `ClickHouseColumn` to return its index. However, its private field `columnIndex` always equals 0 for any write/read path. This field is set in the constructor initially and never updated to reflect the actual column's index - https://github.com/gravity182/clickhouse-java/blob/a3f80b6476c6832a0f8e09c88b65f55e86b4e270/clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java#L670.
Interestingly, this method worked correctly in jdbc-v1. See the implementation - https://github.com/gravity182/clickhouse-java/blob/3ce1b09161e15bfd13695d7fb7bdd198b4672e00/clickhouse-jdbc/src/main/java/c …

Fix `ResultSet#findColumn` - return actual column's index instead of 0

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/JdbcConfigurationTest.java

Restore IPv6 address support in the JDBC URL connection.
Prior to 1.8.0 it was working properly. As of 1.8.x, the `URL_REGEXP` rejected URLs like `jdbc:clickhouse://[::1]/`.

Restore IPv6 address support in the JDBC URL connection.

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/metadata/ResultSetMetaDataImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/metadata/ResultSetMetaDataImplTest.java

https://github.com/ClickHouse/clickhouse-java/issues/2388

[jdbc-v2] Fix NPE in ResultSetMetaDataImpl#getColumnClassName

---

clickhouse-client/pom.xml
jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseParser.g4
jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/DataSourceImpl.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/ParsedPreparedStatement.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
pom.xml

- Adds test for `WITH` clause with parameters to `PreparedStatementImplTests`  
Closes https://github.com/ClickHouse/clickhouse-java/issues/2391

[jdbc-v2] Added test for WITH statement with parameters. 

---

.github/workflows/build.yml
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseSimpleRecordTest.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/metadata/DatabaseMetaDataImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
pom.xml

This PR does a several build changes 
- minimal source version is 17
- minimal target version is 8
- when built with -Dj8 - the JDK 1.8 toolchain is required

[repo] Force using JDK 1.8 toolchain to build for JDK 8 

---

jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseLexer.g4
jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseParser.g4
jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/ParsedPreparedStatement.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/SqlParserTest.java

Adds grammar for cast operation: `?:: integer` or `?::UUID` 
Closes  https://github.com/ClickHouse/clickhouse-java/issues/2422

[jdbc-v2] Fixes arguments with casts

---

client-v2/src/main/java/com/clickhouse/client/api/Client.java
client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java
client-v2/src/test/java/com/clickhouse/client/ClientTests.java
client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
client-v2/src/test/java/com/clickhouse/client/ProxyTests.java
client-v2/src/test/java/com/clickhouse/client/command/CommandTests.java
client-v2/src/test/java/com/clickhouse/client/metadata/MetadataTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/BigDatasetExamples.java
examples/demo-kotlin-service/src/main/kotlin/com/clickhouse/examples/service/Database.kt

- moves setting defaults the the client builder constructor 
- retires `Client.Builder#useNewImplementation()` 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2269

[client-v2] Move default values to Enum

---

jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseParser.g4
jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/ParsedPreparedStatement.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/SqlParserTest.java

Fixes parser grammar for: 
- `SELECT INTERVAL '1 day'` - when interval is define like literal 
- `( WITH .... ) ` - wrapped CTEs 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2431
Closes https://github.com/ClickHouse/clickhouse-java/issues/2429

[jdbc-v2] Fix parser grammar

---

jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseParser.g4
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/SqlParserTest.java

Closes https://github.com/ClickHouse/clickhouse-java/issues/2427 

[jdbc-v2] Adds `source` keyword as one for alias

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/ProcessParser.java
client-v2/src/main/java/com/clickhouse/client/api/internal/Gauge.java
client-v2/src/main/java/com/clickhouse/client/api/metrics/ClientMetrics.java

- Fix bug with incorrect usage of Integer where Long is expected.
Metrics returned from the server can overflow Integer e.g. when elapsed time is higher than 2 seconds (it's in nanoseconds).
- Use generic name instead of specific metric name.
- Update misleading Javadocs for client side metrics.
Stopwatch metrics always convert nanoseconds to milliseconds when getLong() is called on them.

Fix a small bug with server metrics parsing + a few code cleanups.

---

client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/JdbcIntegrationTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/JdbcConfigurationTest.java

Try to support database names with dashes. See https://github.com/ClickHouse/clickhouse-java/issues/2463
Closes https://github.com/ClickHouse/clickhouse-java/issues/2463
- [ ✅  ] Closes #2463
- [ ✅ ] Unit and integration tests covering the common scenarios were added

Database names with dashes

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/JdbcConfigurationTest.java

This PR ensures that valid JDBC URLs are also accepted as endpoints by Client.
JDBC URLs which contain multiple endpoints are considered _invalid_
This is an alternative PR to #2488 which supports the use of multiple endpoints in JDBC URLs.
- [ ✅  ] Unit and integration tests covering the common scenarios were added

[jdbc-v2] Adds default port and restricts multiple endpoints

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java

The [API doc for Connection](https://docs.oracle.com/en/java/javase/24/docs/api/java.sql/java/sql/Connection.html#isValid(int)) says:
> Returns true if the connection has not been closed and is still valid. The driver shall submit a query on the connection or use some other mechanism that positively verifies the connection is still valid when this method is called.
1. Do not throw Exception when connection is closed.
2. Check that connection may be used to perform queries.
`Client` already provides ping method with timeout which is used here.
Closes #2472 
- [ ✅ ] Closes #2472
- [ ✅ ] Unit and integration tests covering the common scenarios were added

Implement Connection#isValid

---

client-v2/src/test/java/com/clickhouse/client/ParameterizedQueryTest.java

Tests are failing when performed against ClickHouse cloud. I _think_ that this is related to `Memory` table engine. This PR changes test table DDL to use standard `MergeTree` engine.

Make test work with ClickHouse Cloud

---

clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java
clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataType.java
clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseColumnTest.java
client-v2/src/main/java/com/clickhouse/client/api/DataTypeUtils.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/SerializerUtils.java
client-v2/src/test/java/com/clickhouse/client/datatypes/DataTypeTests.java
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java
pom.xml

- Adds support for new Time and Time64 types in the client 
- Adds support for the types to be written to a Variant and Dynamic columns
Closes https://github.com/ClickHouse/clickhouse-java/issues/2460

[client-v2, jdbc-v2] Support for Time and Time64 

---

jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseParser.g4
jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/ParsedPreparedStatement.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/SqlParserTest.java

This PR does fixes in parser grammar to handle:
1. CTE with unbound columns
2. IN expressions like "SELECT * FROM t WHERE v in (?)" 
3. keyword aliases 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2500
Closes https://github.com/ClickHouse/clickhouse-java/issues/2493
Closes https://github.com/ClickHouse/clickhouse-java/issues/2478
Closes #2504 

[jdbc-v2] Parser issues fix

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java

This PR makes changes the format of `ResultSet.getString()` for Date32, DateTime, and DateTime32 columns to a more traditional format, i.e.
- YYYY-MM-dd for Date / Date32
- YYYY-MM-dd HH:mm:ss for DateTime / DateTime32
This PR does _not_ change any of the existing time zone magic.
Closes #2408 #2448
- [ :heavy_check_mark: ] Closes #2448
- [ :heavy_check_mark:  ] Unit and integration tests covering the common scenarios were added

Adjust format of ResultSet.getString() for DateTime

---

jdbc-v2/src/main/java/com/clickhouse/jdbc/metadata/DatabaseMetaDataImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/metadata/DatabaseMetaDataTest.java

There are some method in metadata that should return empty dataset with specific structure. Previously a single row with default values was returned. This breaks UI tools because they use this data for further work. 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2517

[JDBC-V2] Fix DatabaseMetadata to return empty ResultSet where expected

---

examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java

- Override `clearBatch` for `PreparedStatementImpl`
- Clears the internal batch state immediately after executeBatch() to prevent parameter leakage and enable safe statement reuse.
Closes #2548

[JDBC-V2] fix(`StatementImpl`/`PreparedStatementImpl`): prevent duplicate data insertion by clearing batch after execution for issue-2548

---

clickhouse-jdbc/pom.xml
client-v2/pom.xml
client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java
jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java
performance/src/main/java/com/clickhouse/benchmark/clients/Compression.java
pom.xml

- Shades Antlr Runtime Library. Previously was just added to `-all` jar. 
- corrects package name for other shaded libraries. 
Closes: https://github.com/ClickHouse/clickhouse-java/issues/2553

[repo] Shade Antlr Runtime Library

---

.github/workflows/release.yml
clickhouse-jdbc/pom.xml

When `maven-assemble-plugin` and `maven-shade-plugin` used together then `META-INF/services/java.sql.Driver` entries not merged from jars. 
This PRs moves creating an uber jar to shade plugin and makes it output to `target/bundle` directory. This should prevent publishing uber jar to Maven Central

[repo] Fix all dependencies + shade 

---

client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/SerializerUtils.java

Hi ClickHouse team, I stumbled upon incorrect exception message when I was trying to use `System.currentTimeMillis()` for `ts DateTime('UTC')` COLUMN, Java client crashes with following exception:
```js
Caused by: java.lang.IllegalArgumentException: Cannot convert 1758056775008 to DataTime
at com.clickhouse.client.api.data_formats.internal.SerializerUtils.writeDateTime(SerializerUtils.java:1146)
at com.clickhouse.client.api.data_formats.internal.SerializerUtils.serializePrimitiveData(SerializerUtils.java:548)
at com.clickhouse.client.api.data_formats.internal.SerializerUtils.serializeData(SerializerUtils.java:103)
```
Which of course made me triple-check that I used correct COLUMN type, turns out it is a typo in Java client :)

Fix exception message DataTime → DateTime
