- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSetMetaData.java
Добавил реализацию для метода ` getColumnClassName`. Без нее не проходил mapping в `MyBatis`.
> added implementation for ClickHouseResultSetMetaData.getColumnClassName

- src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
Проглядел этот момент, там возможно неправильное поведение
> added correct handling for exception

- src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
- src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java
удалил дублирование и ненужную синхронизаицию
> removed a useless code

- src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
- src/main/java/ru/yandex/clickhouse/response/StreamSplitter.java
- src/main/java/ru/yandex/clickhouse/util/LogProxy.java
Argument for @NotNull parameter 'types' of com/intellij/database/introspection/jdbcMetadataWrappers/DatabaseMetaDataWrapper.tables
> Bug fix and some extra logging in trace mode

- src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
- src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
I implemented these two functions to enable setting the active schema (database) for the current connection.
> Implemented Connection.getSchema() and setSchema()

- src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
Sorry, my latest commit caused a NPE in some JDBC clients. This fixes it.
> Fix NPE in database metadata

- src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
- src/test/java/ru/yandex/clickhouse/integration/RowBinaryStreamTest.java
- src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStreamTest.java
Долго искал одну неприятную багу. Нашел, параллельно написал ещё пяток тестов.
> Binary format fix and tests

- src/main/java/ru/yandex/clickhouse/response/ByteFragmentUtils.java
- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
- src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
- src/main/java/ru/yandex/clickhouse/util/TypeUtils.java
- src/test/java/ru/yandex/clickhouse/integration/RowBinaryStreamTest.java
- src/test/java/ru/yandex/clickhouse/response/ByteFragmentUtilsTest.java
Here you are. Complete (I hope) support of arrays in clickhouse-jdbc. This solves #107.
I'm relatively new to the codebase so feel free to comment/request for changes in my PR.
> Add arrays support

- src/main/java/ru/yandex/clickhouse/ClickHouseConnection.java
- src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
- src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
use version to determine correct columns
> fix metadata request from system.columns. 

- src/main/java/ru/yandex/clickhouse/response/ByteFragmentUtils.java
- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
- src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
- src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
- src/test/java/ru/yandex/clickhouse/response/ByteFragmentUtilsTest.java
Similar behavior is implemented in the PostgreSQL driver
> Add support for boxed primitive types in arrays

- src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
- src/main/java/ru/yandex/clickhouse/Jackson.java
- src/main/java/ru/yandex/clickhouse/response/ArrayToStringDeserializer.java
Shaved off about 150ms per query.
> Extracted out creation of Jackson's ObjectMapper to thread local

- .travis.yml
- CHANGELOG
- src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java
> Add "with" case to isSelect validation

- src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultBuilder.java
- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
- src/main/java/ru/yandex/clickhouse/response/StreamSplitter.java
- src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetTest.java
Hi guys, since I need this feature quite badly - here's my implementation :) Please review and let me know. Cheers
> Fix for #161

- src/main/java/ru/yandex/clickhouse/util/ClickHouseArrayUtil.java
- src/test/java/ru/yandex/clickhouse/util/ClickHouseArrayUtilTest.java
> #184 - Fix to parse array of arrays for nested structure

- src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java
> Less logging by default

- src/main/java/ru/yandex/clickhouse/PreparedStatementParser.java
- src/test/java/ru/yandex/clickhouse/PreparedStatementParserTest.java
> Fix prepared select statement with parameter in parentheses

- src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
- src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java
> Ignore leading comments when determining the statement type

- src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSetMetaData.java
- src/main/java/ru/yandex/clickhouse/util/TypeUtils.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHouseDatabaseMetadataTest.java
- src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetMetaDataTest.java
- src/test/java/ru/yandex/clickhouse/util/TypeUtilsTest.java
> Use real type names in meta data

- src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
- src/main/java/ru/yandex/clickhouse/PreparedStatementParser.java
- src/test/java/ru/yandex/clickhouse/PreparedStatementParserTest.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java
> Prepared batch inserts: Support constant NULL values

- src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
- src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStreamTest.java
Following up on discussion in https://github.com/apache/beam/pull/7006#discussion_r232695315
@serebrserg can you please take a look?
> Add writeNullable to RowBinaryStream

- src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
- src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java
Insert-quorum params have been added
> MARKETINFRA-3901 Insert-quorum params have been added

- pom.xml
- src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java
- src/main/java/ru/yandex/clickhouse/ClickhouseJdbcUrlParser.java
- src/main/java/ru/yandex/clickhouse/util/ClickHouseVersionNumberUtil.java
- src/main/java/ru/yandex/clickhouse/util/TypeUtils.java
- src/test/java/ru/yandex/clickhouse/ClickhouseJdbcUrlParserTest.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHouseDatabaseMetadataTest.java
- src/test/java/ru/yandex/clickhouse/util/ClickHouseVersionNumberUtilTest.java
- src/test/java/ru/yandex/clickhouse/util/TypeUtilsTest.java
* JDBC URL may contain trailing slash
* Use driver version from MANIFEST instead of constant "0.1"
* Memory is a valid TABLE engine
* Decimal type should be treated as such
> Metadata minor issues

- src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
- src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java
SELECT_SEQUENTIAL_CONSISTENCY param has been added
> MARKETINFRA-3901 SELECT_SEQUENTIAL_CONSISTENCY param has been added

- src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
- src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
This allows to override server value of enable_optimize_predicate_expression on a query level.
> enable_optimize_predicate_expression query param

- src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java
> Simple getMetaData implementation for prepared statement

- src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java
- src/main/java/ru/yandex/clickhouse/except/ClickHouseExceptionSpecifier.java
- src/main/java/ru/yandex/clickhouse/response/ThrowingFunction.java
- src/main/java/ru/yandex/clickhouse/util/Patterns.java
- src/main/java/ru/yandex/clickhouse/util/Utils.java
Small cleanups, mostly removal of unused code.
Also, replaced:
`result.toArray(new DriverPropertyInfo[result.size()]);`
with
`result.toArray(new DriverPropertyInfo[0]);`
due to [this](https://stackoverflow.com/questions/174093/toarraynew-myclass0-or-toarraynew-myclassmylist-size)
> IDE warnings cleanup

- pom.xml
- src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
- src/main/java/ru/yandex/clickhouse/util/ClickHouseArrayUtil.java
- src/main/java/ru/yandex/clickhouse/util/ClickHouseBlockChecksum.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java
- src/test/java/ru/yandex/clickhouse/util/ClickHouseArrayUtilTest.java
moved from #284 to resolve conflicts
> Issue 283 merge

- src/main/java/ru/yandex/clickhouse/PreparedStatementParser.java
- src/test/java/ru/yandex/clickhouse/PreparedStatementParserTest.java
> Prepared statements: Support single and double quotes

- src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
(copied from CH Settings.h #310
> Fix description of use_uncompressed_cache

- src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStream.java
- src/test/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStreamTest.java
> #299 Fixed LEB128 decoding

- src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java
> Implementation of cancel method

- src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
- src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
Added max_memory_usage_for_user & max_memory_usage_for_all_queries settings support into ClickHouseProperties
> Added max_memory_usage_for_user & max_memory_usage_for_all_queries

- src/main/java/ru/yandex/clickhouse/PreparedStatementParser.java
- src/test/java/ru/yandex/clickhouse/PreparedStatementParserTest.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java
> Fix multi-line statement parsing for prepared statements

- src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
- src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
- src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java
Otherwise, JDBC properties aren't propagated.
> Add max_insert_block_size, insert_deduplicate, insert_distributed_sync

- src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
- src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
- src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java
> support max_partitions_per_insert_block param

- src/main/java/ru/yandex/clickhouse/util/TypeUtils.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHouseDatabaseMetadataTest.java
- src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetMetaDataTest.java
- src/test/java/ru/yandex/clickhouse/util/TypeUtilsTest.java
Support DateTime columns with explicit timezones. Fix #329
> Improve Detection of DateTime Columns

- src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java
> Fix strict SSL mode

- src/main/java/ru/yandex/clickhouse/response/ByteFragmentUtils.java
- src/test/java/ru/yandex/clickhouse/integration/ArrayTest.java
- src/test/java/ru/yandex/clickhouse/response/ByteFragmentUtilsTest.java
This pull-request adding support for array of decimals.
> Add support for array of decimals

- src/main/java/ru/yandex/clickhouse/BalancedClickhouseDataSource.java
- src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
- src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementImpl.java
- src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
- src/main/java/ru/yandex/clickhouse/except/ClickHouseExceptionSpecifier.java
- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
- src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java
- src/main/java/ru/yandex/clickhouse/util/guava/StreamUtils.java
This pr contains several mirror fixes:
- fix NPE,
- close resources,
- improve logging without necessary concatenation
> Small improvements

- src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java
These methods are only declared as abstract but aren't implemented.
> Add getTimestamp with Calendar

- src/main/java/ru/yandex/clickhouse/ClickHouseDataSource.java
- src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java
- src/main/java/ru/yandex/clickhouse/response/FastByteArrayOutputStream.java
- src/main/java/ru/yandex/clickhouse/util/ClickHouseArrayUtil.java
- src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStream.java
- src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java
- src/main/java/ru/yandex/clickhouse/util/Utils.java
> fix Javadoc

- .travis.yml
> Try Bionic distributive

- src/test/java/ru/yandex/clickhouse/integration/NativeStreamTest.java
- src/test/java/ru/yandex/clickhouse/integration/RowBinaryStreamTest.java
problems: before 19.15 it was broken insert lowCardinality in native stream
> Test lowCardinality

- src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java
- src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java
- src/test/java/ru/yandex/clickhouse/settings/ClickHousePropertiesTest.java
Added any_join_distinct_right_table_keys field in ClickHouseProperties, see (https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#backward-incompatible-change-3)
> Added any_join_distinct_right_table_keys field in ClickHouseProperties

- src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java
- src/test/java/ru/yandex/clickhouse/ClickHouseStatementTest.java
- src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java
fixes #208 - Result without columns by adding a new line before format
> fixes #208 - Result without columns by adding a new line before format

- .travis.yml
- src/main/java/ru/yandex/clickhouse/response/FastByteArrayOutputStream.java
> update supported JDK

- src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java
test for large external data (100 rows) 
// some user complained in a chat that jdbc issue have such issue. But I could not reproduce, and made this test
> test for large external data

- clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java
> Test UUID Array

- .github/workflows/release.yml
Update action flow to support multi-release jars
> Multi-release jars

- .github/workflows/analysis.yml
- .github/workflows/benchmark.yml
- clickhouse-benchmark/src/main/java/com/clickhouse/benchmark/jdbc/ConsumeValueFunction.java
- clickhouse-benchmark/src/main/java/com/clickhouse/benchmark/jdbc/DriverState.java
- clickhouse-benchmark/src/main/java/com/clickhouse/benchmark/jdbc/JdbcDriver.java
- clickhouse-benchmark/src/main/java/com/clickhouse/benchmark/jdbc/Query.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseChecker.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseDataProcessor.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseDataStreamFactory.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseDeserializer.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseInputStream.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValues.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/BinaryStreamUtils.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseBigDecimalValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHousePipedStream.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseRowBinaryProcessor.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseStreamResponse.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseStringValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseTabSeparatedProcessor.java
- clickhouse-client/src/test/java/com/clickhouse/client/data/BinaryStreamUtilsTest.java
- clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcResponse.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpResponse.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseConnection.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseResultSet.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/FakeTransaction.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/StreamBasedPreparedStatement.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/CombinedResultSetTest.java
* update benchmarks to cover more data types
* remove checkstyle for duplicated with sonar
* refine code for tiny reads
> Benchmarking

- clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/util/UtilsTest.java
This is derived from PR #747 focusing on below items:
* multiple values for batch insertion
* leverage JDBC escape syntax and external table for non-insert query(in a similar way as input function based approach)
> Enhance new JDBC driver

- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseEmptyValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseStreamResponse.java
- clickhouse-client/src/test/java/com/clickhouse/client/data/ClickhouseLZ4InputStreamTest.java
And add more tests for LZ4 input stream
> Treat Nothing as NULL

- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseColumn.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseDataType.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseDateTimeValue.java
- clickhouse-jdbc/legacy.xml
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/InputBasedPreparedStatement.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/TableBasedPreparedStatement.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
- clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/response/ClickHouseResultSetTest.java
- clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/response/parser/ClickHouseValueParserTest.java
* Add `SimpleAggregateFunction` data type
* Enhance executeBatch, executeQuery and executeUpdate methods
* Use separate thread to cancel statement
* A few more integration test
> Fix minor issues found after 0.3.2 pre-release

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseResultSet.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseResultSetTest.java
- third-party-libraries/pom.xml
* add unit test for #797
* bump 3rd party dependencies
> Prepare patch release

- README.md
- clickhouse-client/README.md
- clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcClient.java
- clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcFuture.java
- clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseStreamObserver.java
- clickhouse-jdbc/README.md
- examples/grpc/pom.xml
- examples/grpc/src/main/java/com/clickhouse/examples/jdbc/Main.java
- examples/jdbc/pom.xml
- examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Advance.java
- examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java
- pom.xml
* add JDBC and gRPC examples
* bump dependencies
* minor changes to gRPC client to produce less logs and consider socket timeout in query/insert
> Prepare 0.3.2-patch1 release

- clickhouse-jdbc/src/main/javacc/ClickHouseSqlParser.jj
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
> Consider CTE when parsing insert statement

- README.md
- clickhouse-benchmark/pom.xml
- clickhouse-client/README.md
- clickhouse-jdbc/README.md
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
- examples/grpc/pom.xml
- examples/jdbc/pom.xml
- pom.xml
* Bump versions
* Update README to include benchmark results
* Throw SQLException in Statement.executeUpdate()
* Support `continueBatchOnError` in Statement.executeBatch()
> Prepare patch5

- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseRowBinaryProcessor.java
> Fix key type when deserializing map objects

- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseColumn.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseDataType.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseColumnTest.java
> Fix issue when parsing multi-word data type

- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
Workaround for ClickHouse/ClickHouse#36994
> Fix build failure on 22.4

- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseArrayValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseBitmapValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseGeoMultiPolygonValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseGeoPointValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseGeoPolygonValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseGeoRingValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseNestedValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseTupleValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseByteArrayValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseDoubleArrayValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseFloatArrayValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseIntArrayValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseLongArrayValue.java
- clickhouse-client/src/main/java/com/clickhouse/client/data/array/ClickHouseShortArrayValue.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseResultSetTest.java
> Return null instead of default value for nullable types

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/InputBasedPreparedStatement.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/TableBasedPreparedStatement.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
> implement getParameterMetadata method in PreparedStatement

- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseFile.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseInputStream.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseOutputStream.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/HttpUrlConnectionImpl.java
- clickhouse-http-client/src/main/java11/com/clickhouse/client/http/HttpClientConnectionImpl.java
- clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpConnectionTest.java
> support direct upload/download in http client

- clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseBitmap.java
- clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseBitmap.java
https://github.com/ClickHouse/clickhouse-jdbc/issues/918#issue-1227574374
> Fix Roaring64NavigableMap reading mismatches

- README.md
- clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseServerForTest.java
> Update doc for build and testing

- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseResponseSummary.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
> Return read/written rows whenever possible

- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseColumn.java
> Fix issue of parsing SimpleAggregateFunction column

- clickhouse-client/src/test/java/com/clickhouse/client/BaseIntegrationTest.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnectionFactory.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/HttpUrlConnectionImpl.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
- clickhouse-http-client/src/main/java11/com/clickhouse/client/http/ClickHouseHttpConnectionFactory.java
- clickhouse-http-client/src/main/java11/com/clickhouse/client/http/HttpClientConnectionImpl.java
- clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpClientTest.java
> Respect custom Authorization header in clickhouse-http-client

- clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/ClickHouseCommandLine.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseRequest.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
> Respect custom format when importing file

- clickhouse-jdbc/README.md
> Example to show how to use custom setting in new driver

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseResultSet.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseResultSetTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/CombinedResultSetTest.java
> Allow negative fetch size

- clickhouse-jdbc/src/main/javacc/ClickHouseSqlParser.jj
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/parser/ClickHouseSqlParserTest.java
> Fix issue of parsing insert with settings

- .github/workflows/analysis.yml
- .github/workflows/benchmark.yml
fix [security advisories](/ClickHouse/clickhouse-jdbc/security/advisories/GHSA-g846-pr54-8f3v) from @santrancisco.
> fix security advisories

- .github/pull_request_template.md
with a checklist to confirm the high quality of changes
> add a pr template

- CHANGELOG.md
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java
- clickhouse-data/src/main/java/com/clickhouse/data/format/BinaryDataProcessor.java
- clickhouse-data/src/main/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessor.java
- clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseColumnTest.java
- clickhouse-data/src/test/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessorTest.java
Fix serde issue of FixedString(n) in nested data structure
> Fix serde issue of FixedString(n) in nested data structure

- clickhouse-jdbc/docs/datetime.md
- examples/r2dbc/misc/docker/clickhouse-docker-mount/config.xml
- examples/r2dbc/misc/docker/clickhouse-docker-mount/users.xml
Change repositiry name in r2dbc docker config file 
Change server names from yandex.yu to clickhouse.com
> change repo name in config files

- CHANGELOG.md
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseNestedValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseTupleValue.java
- clickhouse-data/src/test/java/com/clickhouse/data/value/ClickHouseNestedValueTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
Fix the bug while converting nested values to Java maps.
> Fix the bug while converting nested values to Java maps

- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
Remove redundant socket options in `ApacheHttpConnectionImpl`.
> remove redundant socket options

- .github/workflows/third_party_libs.yml
- third-party-libraries/org.apache.commons.compress/pom.xml
- third-party-libraries/org.apache.commons.compress/src/main/java/module-info.java
- third-party-libraries/org.apache.commons.compress/src/main/java/org/apache/commons/compress/DummyClass.java
- third-party-libraries/org.apache.commons.compress/src/main/java/org/apache/commons/compress/compressors/DummyClass.java
- third-party-libraries/org.apache.commons.compress/src/main/java/org/apache/commons/compress/compressors/bzip2/DummyClass.java
- third-party-libraries/org.apache.commons.compress/src/main/java/org/apache/commons/compress/compressors/deflate/DummyClass.java
- third-party-libraries/org.apache.commons.compress/src/main/java/org/apache/commons/compress/compressors/gzip/DummyClass.java
- third-party-libraries/org.apache.commons.compress/src/main/java/org/apache/commons/compress/compressors/lz4/DummyClass.java
- third-party-libraries/org.apache.commons.compress/src/main/java/org/apache/commons/compress/compressors/snappy/DummyClass.java
- third-party-libraries/pom.xml
Add alias of commons-compress and bump version.
> Add alias of commons-compress and bump version

- .github/workflows/analysis.yml
- .github/workflows/build.yml
- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
- clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseFileTest.java
- clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseUtilsTest.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/Main.java
- examples/r2dbc/clickhouse-r2dbc-spring-webflux-sample/pom.xml
- pom.xml
- third-party-libraries/org.apache.commons.compress/pom.xml
Bump dependencies and update build scripts
> Bump dependencies and update build scripts

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/Main.java
Discard security warnings for test class
> Discard security warnings for test class

- CHANGELOG.md
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaData.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseResultSet.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseResultSetMetaData.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/JdbcConfig.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
New option for catalog support.
> new option for catalog support

- CHANGELOG.md
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseConnection.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
Change catalog/schema in JDBC driver for USE statement.
> Change catalog/schema in JDBC driver for USE statement

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseConnection.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java
- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
Check database existence when changing catalog/schema. A follow up PR for #1287.
> check database existence when changing catalog/schema

- clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/ClickHouseCommandLineClient.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClientBuilder.java
- clickhouse-client/src/main/java/com/clickhouse/client/UnsupportedProtocolException.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseCompressionAlgorithm.java
- clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcClient.java
- clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcClientImpl.java
- clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/FramedLZ4Utils.java
improve error handling when missing lib
> improve error handling when missing lib

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
Add ! suffix and enhance error handling for #1291.
> Add ! suffix and enhance error handling

- .github/workflows/build.yml
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseConnectionTest.java
> Fix build failure

- CHANGELOG.md
- clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/ClickHouseStatement.java
- clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/connection/ClickHouseConnection.java
- clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/connection/ClickHouseConnectionFactory.java
- clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/connection/ClickHouseConnectionFactoryProvider.java
- clickhouse-r2dbc/src/test/java/com/clickhouse/r2dbc/BaseR2dbcTest.java
- clickhouse-r2dbc/src/test/java/com/clickhouse/r2dbc/connection/ClickHouseConnectionTest.java
Enhance r2dbc driver to support all client options.
> Enhance r2dbc driver

- CHANGELOG.md
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseValues.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseArrayValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBigDecimalValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBigIntegerValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmapValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseByteValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseDateTimeValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseDateValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseDoubleValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseEnumValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseFloatValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseInstantValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseIntegerValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseLongValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseMapValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseNestedValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseOffsetDateTimeValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseShortValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseTupleValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseUuidValue.java
- clickhouse-data/src/test/java/com/clickhouse/data/value/ClickHouseStringValueTest.java
converts empty string to default value
> converts empty string to default value

- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
Promote `apache-http-client` performance. This PR try to close #1320 
1.use BasicHttpClientConnectionManager instead of PoolingHttpClientConnectionManager
2.make `ApacheHttpConnectionImpl` un-reusable.
1. clickhouse-jdbc 
```
Benchmark                (client)  (connection)  (statement)   (type)   Mode  Cnt     Score     Error  Units
Query.selectInt8  clickhouse-jdbc         reuse       normal  default  thrpt   20  2269.340 ± 303.895  ops/s
Query.selectInt8  clickhouse-jdbc         reuse     prepared  default  thrpt   20  2312.906 ± 188.955  ops/s
```
2. clickhouse-apache-http-client-jdbc(new)
```
Benchmark                                   (client)  (connection)  (statement)   (type)   Mode  Cnt     Score     Error  Units
Query.selectInt8  clickhouse-apache-http-client-jdbc         reuse …
```
> Promote `apache-http-client` performance

- pom.xml
> Upgrade MySQL JDBC from 8.0.32 to 8.0.33

- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
Add more tests for response input stream and nested array in tuple.
> add more tests

- CHANGELOG.md
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseSslContextProvider.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseSslContextProviderTest.java
Extensible SSL context provider
> Extensible SSL context provider

- third-party-libraries/pom.xml
> bump 3rd party libs

- CHANGELOG.md
- clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/config/ClickHouseCommandLineOption.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNode.java
- clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
- clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseDefaults.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseConfigTest.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseNodeTest.java
- clickhouse-data/src/main/java/com/clickhouse/config/ClickHouseDefaultOption.java
- clickhouse-data/src/main/java/com/clickhouse/config/ClickHouseOption.java
- clickhouse-data/src/test/java/com/clickhouse/config/ClickHouseOptionTest.java
- clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/config/ClickHouseGrpcOption.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
> Mask sensitive option in log

- README.md
- examples/client/src/main/java/com/clickhouse/examples/jdbc/Main.java
Update readme and client example.
> Update readme and client example

- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
Add tests to cover insert AggregateFunction and column with default value.
> Add tests to cover insert AggregateFunction and column with default value

- CHANGELOG.md
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseUtils.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnectionFactory.java
- clickhouse-http-client/src/main/java11/com/clickhouse/client/http/ClickHouseHttpConnectionFactory.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
Improve error handling for invalid query.
> improve error handling for invalid query

- clickhouse-data/src/main/java/com/clickhouse/data/ByteUtils.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseByteBuffer.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseByteUtils.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseCompressionAlgorithm.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataProcessor.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseInputStream.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseUtils.java
- clickhouse-data/src/main/java/com/clickhouse/data/DelegatedInputStream.java
- clickhouse-data/src/main/java/com/clickhouse/data/format/BinaryStreamUtils.java
- clickhouse-data/src/main/java/com/clickhouse/data/stream/AbstractByteArrayInputStream.java
- clickhouse-data/src/main/java/com/clickhouse/data/stream/AbstractByteBufferInputStream.java
- clickhouse-data/src/main/java/com/clickhouse/data/stream/EmptyInputStream.java
- clickhouse-data/src/main/java/com/clickhouse/data/stream/Lz4InputStream.java
- clickhouse-data/src/main/java/com/clickhouse/data/stream/Lz4OutputStream.java
- clickhouse-data/src/main/java9/com/clickhouse/data/ByteUtils.java
- clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseByteBufferTest.java
- clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseByteUtilsTest.java
- clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseUtilsTest.java
- clickhouse-data/src/test/java/com/clickhouse/data/stream/InputStreamImplTest.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
Add methods to scan input stream.
> Add methods to scan input stream

- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
> Add test for nested arrays

- third-party-libraries/pom.xml
> Upgrade 3rd party libs

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/CombinedResultSet.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/CombinedResultSetTest.java
Fix bugs in *First and *Last methods in CombinedResultSet and add more tests.
> Add more tests for CombinedResultSet

- clickhouse-grpc-client/src/main/java9/module-info.java
- examples/client/pom.xml
- examples/client/src/main/java/com/clickhouse/examples/jdbc/Main.java
- examples/jdbc/pom.xml
- pom.xml
> Bump dependencies

- CHANGELOG.md
- clickhouse-data/src/main/java/com/clickhouse/data/mapper/CustomRecordMappers.java
Fix parameter position typo as reported in #1417
> fix parameter position typo - #1417

- pom.xml
As part of our effort to fix our nightly automation process, we should downgrade this problematic version.
> Downgrading Source-Plugin version

- .github/workflows/release.yml
add permissions: write-all to release workflow
> add permissions: write-all to release workflow

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CHANGELOG.md
- pom.xml
> Prepare next version 0.5.1

- .github/workflows/build.yml
- clickhouse-cli-client/src/test/java/com/clickhouse/client/cli/ClickHouseCommandLineClientTest.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataStreamFactory.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseFormat.java
- clickhouse-grpc-client/src/test/java/com/clickhouse/client/grpc/ClickHouseGrpcClientTest.java
Adding support for RowBinaryWithDefaults
> Add support in RowBinaryWithDefaults

- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java
- clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpClientTest.java
- clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpConnectionTest.java
> Remove WEB_CONTEXT support #1512

- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java
> Stabilize test gettables

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CHANGELOG.md
- pom.xml
> bump version to 0.6.0

- CHANGELOG.md
- README.md
- clickhouse-cli-client/README.md
- clickhouse-cli-client/pom.xml
- clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/ClickHouseCommandLine.java
- clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/ClickHouseCommandLineClient.java
- clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/ClickHouseCommandLineResponse.java
- clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/config/ClickHouseCommandLineOption.java
- clickhouse-cli-client/src/test/java/com/clickhouse/client/cli/ClickHouseCommandLineClientTest.java
- pom.xml
Prepare CLI package for depreciation
> Prepare CLI package for depreciation

- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseSimpleRecord.java
Optimize read data by column name
> Optimize read data by column name

- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
This PR is just to fix the build issue. However there much complex issue https://github.com/ClickHouse/clickhouse-java/issues/650
> Fix testErrorDuringQuery 

- CHANGELOG.md
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseFormat.java
Change RowBinaryWithDefaults settings
> Change RowBinaryWithDefaults settings

- client-v2/pom.xml
- client-v2/src/main/java/com/clickhouse/client/api/Client.java
Connection settings for new API.
> Connection settings new api

- client-v2/pom.xml
- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/ClientSettings.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/SettingsConverter.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/ValidationUtils.java
- client-v2/src/main/java/com/clickhouse/client/api/query/QueryResponse.java
- client-v2/src/main/java/com/clickhouse/client/api/query/QuerySettings.java
- client-v2/src/test/java/com/clickhouse/client/SettingsTests.java
- client-v2/src/test/java/com/clickhouse/client/metadata/MetadataTests.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
Added query settings from existing client. 
Implemented simple validation methods
> Added all query settings and implemented simple validation

- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
There are 3 annoying files in the root of the project are left by tests.
> Cleanup after Tests!

- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
> #1631 Implemented test in more stable way

- client-v2/src/main/java/com/clickhouse/client/api/DataTypeUtils.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReader.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesAndTypesFormatReader.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/BinaryStreamReader.java
- client-v2/src/main/java/com/clickhouse/client/api/query/NullValueException.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
Test major data types and fix related bugs
> [client-v2] Complete Query API

- client-v2/src/main/java/com/clickhouse/client/api/data_formats/ClickHouseBinaryFormatReader.java
Fixed javadoc blocking release
> Fixed javadocs

- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/SettingsConverter.java
- client-v2/src/main/java/com/clickhouse/client/api/query/QueryResponse.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
- Added shorter version for query operation (with query only, with query and settings)
- Fixed sending named parameters via http
- Updated tests to use proper query method.
> [client-v2] Query API With Query Parameters

- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/insert/InsertSettings.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/ValidationUtils.java
- client-v2/src/main/java/com/clickhouse/client/api/query/QuerySettings.java
- client-v2/src/test/java/com/clickhouse/client/SettingsTests.java
- client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
- client-v2/src/test/java/com/clickhouse/client/metadata/MetadataTests.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
> [client-v2] Settings 

- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
- examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/SimpleReader.java
Simple fix for the next day build :-)
> Removed using new java api in tests to fix nightly build

- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
There was a problem with CompletableFuture wrapping action incorrectly so exception get lost.
> Added proper exception handling for query

- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/RowBinaryWithNamesAndTypesFormatReader.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
> Fix query API various issues

- client-v2/src/main/java/com/clickhouse/client/api/query/Records.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
Make Records class to have same metrics methods that other response classes
> Added metrics to the Records class

- client-v2/src/main/java/com/clickhouse/client/api/internal/SettingsConverter.java
Adding describe_include_subcolumns to REQUEST_SETTINGS
> Adding describe_include_subcolumns to REQUEST_SETTINGS

- client-v2/src/main/java/com/clickhouse/client/api/internal/SettingsConverter.java
adding allow_experimental_variant_type settings
> adding allow_experimental_variant_type settings

- .github/workflows/nightly.yml
- client-v2/src/test/java/com/clickhouse/client/ProxyTests.java
> fix nightly build

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- pom.xml
Fixed release workflow to use generated token
> updated workflows to use token

- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/Main.java
- examples/client-v2/src/main/java/com/clickhouse/examples/client_v2/SimpleReader.java
Adding more examples of the query API
> Add more v2 examples

- .github/workflows/nightly.yml
- .github/workflows/release.yml
Updated nightly and release workflows with new release version
> Update release version for nightly and release WF

- client-v2/src/main/java/com/clickhouse/client/api/Client.java
Add in addEndpoint detection of SSL from URL string
> Add in addEndpoint detection of SSL from URL string

- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseRequest.java
- clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/enums/Protocol.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/SettingsConverter.java
- client-v2/src/main/java/com/clickhouse/client/api/query/QueryResponse.java
- client-v2/src/main/java/com/clickhouse/client/api/query/Records.java
- client-v2/src/test/java/com/clickhouse/client/ClientTests.java
- Fixed handling async operations 
- Minimized number of threads when calling an old client
- Fixed passing custom settings to server (no more check if settings is enabled) 
> [clientk-v2] Fix async issues 

- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/test/java/com/clickhouse/client/ClientTests.java
- client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
`com.clickhouse.client.api.Client` should implement `Closeable` to make it possible to free resources.
> [client-v2] Make client autocloseable to free resources

- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpProto.java
- client-v2/pom.xml
- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/insert/InsertResponse.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
- client-v2/src/test/java/com/clickhouse/client/ProxyTests.java
- client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
Implement Insert of POJOs with new HTTP implementation
> [client-v2] Implement Insert of POJOs with new HTTP implementation

- .github/workflows/analysis.yml
- .github/workflows/build.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
Updated all versions of used `actions/*`
> [maintenance] updated actions/* versions to latest

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java
Closes https://github.com/ClickHouse/clickhouse-java/issues/1776
> Revert check for updateResult()

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CHANGELOG.md
- examples/client-v2/pom.xml
- examples/client/pom.xml
- examples/demo-service/build.gradle.kts
- examples/jdbc/pom.xml
- pom.xml
Updated changelog and versions in examples 
> Pre 0.6.5 

- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/metadata/ColumnToMethodMatchingStrategy.java
- client-v2/src/main/java/com/clickhouse/client/api/metadata/DefaultColumnToMethodMatchingStrategy.java
- client-v2/src/test/java/com/clickhouse/client/metadata/MetadataTests.java
Implemented an option to define how POJO methods should be mapped to columns. 
Closes: https://github.com/ClickHouse/clickhouse-java/issues/1866
> [client-v2] Column to POJO method matching settings

- clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDriver.java
This is replica of https://github.com/ClickHouse/clickhouse-java/pull/1890 to fix some issues.
> [jdbc] framework detection

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CHANGELOG.md
- examples/client-v2/pom.xml
- examples/client/pom.xml
- examples/demo-kotlin-service/build.gradle.kts
- examples/demo-service/build.gradle.kts
- examples/jdbc/pom.xml
- examples/r2dbc/clickhouse-r2dbc-spring-webflux-sample/pom.xml
- pom.xml
- Changelog updated 
- Dependencies updated
> pre 0.7.1 

- client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
- client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
When 404 happens it is compressed.
> [client-v2] Fixed issue with 404 error message

- .github/workflows/build.yml
- CHANGELOG.md
- examples/client-v2/pom.xml
- examples/client/pom.xml
- examples/demo-kotlin-service/build.gradle.kts
- examples/demo-service/build.gradle.kts
- examples/jdbc/pom.xml
- pom.xml
> Pre 0.7.1-patch1

- CHANGELOG.md
- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java
- clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/HttpUrlConnectionImpl.java
Add basic auth support (username/password) for proxy
- [ X] A human-readable description of the changes was provided to include in CHANGELOG
> Proxy auth

- clickhouse-jdbc/pom.xml
- client-v2/pom.xml
- examples/client-v2/pom.xml
- examples/demo-kotlin-service/build.gradle.kts
- examples/demo-service/build.gradle.kts
- examples/jdbc/README.md
- examples/jdbc/pom.xml
- examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Advanced.java
- examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java
- jdbc-v2/pom.xml
Relates to: https://github.com/ClickHouse/clickhouse-java/issues/1927
> [repo] Created shaded all packages and updated examples.

- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/JdbcConfigurationTest.java
> Adjusting how we clean urls

- client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/MapBackedRecord.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/NumberConverter.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/ResultSetImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/types/Array.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java
This PR makes it possible to convert String to numbers.
> [client-v2] String to Number convertion

- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
> [jdbc-v2] Fix convert to toList()

- .github/pull_request_template.md
Extend PR checklist with a link to a parent issue
> add a link to parent issue

- .github/ISSUE_TEMPLATE/feature_request.md
To provide a structure for an  enhancement request
> [repo] Add a template for enhancement request

- .github/workflows/build.yml
- clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseServerForTest.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/ProcessParser.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/ServerSettings.java
- client-v2/src/test/java/com/clickhouse/client/ClientTests.java
- client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
- client-v2/src/test/java/com/clickhouse/client/ProxyTests.java
- client-v2/src/test/java/com/clickhouse/client/command/CommandTests.java
- client-v2/src/test/java/com/clickhouse/client/insert/InsertClientContentCompressionTests.java
- client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
- client-v2/src/test/java/com/clickhouse/client/insert/SamplePOJO.java
- client-v2/src/test/java/com/clickhouse/client/metadata/MetadataTests.java
- client-v2/src/test/java/com/clickhouse/client/query/QuerySamplePOJO.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/metadata/DatabaseMetaData.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/JdbcIntegrationTest.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/metadata/DatabaseMetaDataTest.java
- jwt-gen.js
- cloud tests
- shorter time for compile step (turned off IT tests that are run later)
- JWT setup with all correct env variables
- fixed Statement to set ASYNC_INSERT=0
> [repo] Added cloud tests for jdbc-2 client-2

- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcUtils.java
Adding an array to conversion list and fixing `testPrimitiveArrays` test
> Adding array to conversion list

- clickhouse-client/pom.xml
- clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java
- clickhouse-client/src/main/resources/clickhouse-client-version.properties
- clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseConfigTest.java
- clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpClientTest.java
- clickhouse-jdbc/src/main/resources/clickhouse-jdbc-version.properties
- client-v2/pom.xml
- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java
- client-v2/src/main/java/com/clickhouse/client/api/insert/InsertSettings.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
- client-v2/src/main/java/com/clickhouse/client/api/query/QuerySettings.java
- client-v2/src/main/resources/client-v2-version.properties
- client-v2/src/test/java/com/clickhouse/client/ClientTests.java
- client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
- client-v2/src/test/java/com/clickhouse/client/SettingsTests.java
- jdbc-v2/pom.xml
- jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/Driver.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
- jdbc-v2/src/main/resources/jdbc-v2-version.properties
- jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/DriverTest.java
- pom.xml
Fixes several issues:
- client-v2 old `product_name` property should be alias to a new one `client_name`
- client-v2 client name update 
- jdbc-v2 proper setting client name thru application name 
> [client-v2] Fix user agent

- .github/workflows/build.yml
- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java
- jdbc-v2/pom.xml
- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/DriverProperties.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java
Adding support to JWT in JDBC V2
> Adding support to JWT in JDBC V2

- pom.xml
Publishing to Maven requires at least one developer in the list of package developers. 
> [repo] Restored developers list

- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcUtils.java
> Add a boolean to type mapping

- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcUtils.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
* Adds Array to the conversion list
* Updates the unit tests to actually check for Array
> Support Array conversion

- .github/workflows/build.yml
- client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
> [repo] Fix JWT tests 

- .github/workflows/analysis.yml
- pom.xml
> [repo] added code coverage for sonar

- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseFormat.java
Added format type is not suitable for input but used as output. 
Closes https://github.com/ClickHouse/clickhouse-java/issues/1380
> [client] Adds PrettyJSONEachRow to the formats list

- clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseRequest.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClickHouseServerForTest.java
- clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
- clickhouse-client/src/test/resources/containers/clickhouse-server/users.d/users.xml
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpClient.java
- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java
- clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpClientTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/AccessManagementTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseConnectionTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDataSourceTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDriverTest.java
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/JdbcIntegrationTest.java
- clickhouse-r2dbc/src/test/java/com/clickhouse/r2dbc/spi/test/R2DBCTestKitImplTest.java
- client-v2/src/test/java/com/clickhouse/client/HttpTransportTests.java
- client-v2/src/test/java/com/clickhouse/client/ProxyTests.java
- client-v2/src/test/java/com/clickhouse/client/datatypes/DataTypeTests.java
- client-v2/src/test/java/com/clickhouse/client/insert/InsertClientContentCompressionTests.java
- client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/ConnectionTest.java
After fix in the latest release of CH there is no default "" passwords anymore - so all tests should be fixed :-) 
This PR does exactly that. 
> [repo] fixed tests for no_password problem

- jdbc-v2/src/main/java/com/clickhouse/jdbc/metadata/ResultSetMetaData.java
Implement the getColumnClassName method to accommodate Spring Jdbc and Mybatis
https://github.com/ClickHouse/clickhouse-java/pull/2113
Closes: https://github.com/ClickHouse/clickhouse-java/issues/2112
> feat: implemented getColumnClassName

- clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java
- client-v2/src/test/java/com/clickhouse/client/datatypes/DataTypeTests.java
- client-v2/src/test/java/com/clickhouse/client/query/QueryTests.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java
> [client-v1,v2] Small fix and change in tests

- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseEnum.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmap.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseGeoMultiPolygonValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseGeoPointValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseGeoPolygonValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseGeoRingValue.java
- clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseObjectValue.java
- client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java
This PR fixes compression tests. 
And un-deprecates some classes that are used in V2 in public interface. 
> [client-v2, jdbc-v2] Fixed compression test

- README.md
- Corrected "About" wording 
- Updated sections regarding Client v2 to make it main component 
- Removed examples as they need to be updated what doesn't make sense when there is documentation and source code
- Added documentation links
- Moved old projects to the bottom 
Closes 
> [repo] Update README.md

- jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
enhance insert with different types. (int8, int16, int32, int 64, float, double, string, boolean )
> enhance insert with different types.

- performance/pom.xml
- performance/src/test/com/clickhouse/benchmark/clients/BenchmarkBase.java
- performance/src/test/com/clickhouse/benchmark/clients/InsertClient.java
Add logging JMH & expose the dataset for external usage 
> Add logging JMH & expose the dataset for external usage 

- performance/src/test/com/clickhouse/benchmark/BenchmarkRunner.java
- performance/src/test/com/clickhouse/benchmark/clients/BenchmarkBase.java
- performance/src/test/com/clickhouse/benchmark/clients/InsertClient.java
- performance/src/test/com/clickhouse/benchmark/clients/QueryClient.java
> corrected v1 tests and config to match v2

- performance/src/test/com/clickhouse/benchmark/clients/InsertClient.java
> [perf-test] Cleanup compress settings to have pure default tests

- client-v2/src/main/java/com/clickhouse/client/api/metadata/TableSchema.java
- performance/src/test/com/clickhouse/benchmark/clients/Components.java
- performance/src/test/com/clickhouse/benchmark/clients/InsertClient.java
- performance/src/test/com/clickhouse/benchmark/data/DataSet.java
- performance/src/test/com/clickhouse/benchmark/data/FileDataSet.java
- performance/src/test/com/clickhouse/benchmark/data/SimpleDataSet.java
Add only Serializer benchmark for V1 and V2
> Add only Serializer benchmark for V1 and V2

- client-v2/src/main/java/com/clickhouse/client/api/metadata/DefaultColumnToMethodMatchingStrategy.java
Sorry I know it's a super trivial change but it caught my eyes while reading the source code and fixing it took less time than writing this description
> Fix typo in param

- performance/src/test/com/clickhouse/benchmark/clients/BenchmarkBase.java
> fix JDBC v2 url retrieval 

- performance/src/test/com/clickhouse/benchmark/clients/BenchmarkBase.java
> Fix JDBC v2 url for cloud

- clickhouse-jdbc/pom.xml
- client-v2/pom.xml
- client-v2/src/main/java/com/clickhouse/client/api/Client.java
- client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/ClickHouseLZ4InputStream.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/ClickHouseLZ4OutputStream.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java
- client-v2/src/main/java/com/clickhouse/client/api/internal/LZ4Entity.java
- client-v2/src/test/java/com/clickhouse/client/ClientTests.java
- jdbc-v2/pom.xml
- performance/src/test/com/clickhouse/benchmark/BenchmarkRunner.java
- performance/src/test/com/clickhouse/benchmark/clients/BenchmarkBase.java
- performance/src/test/com/clickhouse/benchmark/clients/Compression.java
- performance/src/test/com/clickhouse/benchmark/clients/CompressorCompare.java
- pom.xml
- use the lz4-java that also has the native implementation 
- disable native compression if needed since the code try to load first native, unsafe, safe 
Closes #2274 
> Improve compression

- jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java
> Clean empty lines in sql query

- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java
- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataType.java
- clickhouse-data/src/test/java/com/clickhouse/data/ClickHouseColumnTest.java
- clickhouse-jdbc/pom.xml
- clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java
- client-v2/src/test/java/com/clickhouse/client/datatypes/DataTypeTests.java
- jdbc-v2/pom.xml
- jdbc-v2/src/main/java/com/clickhouse/jdbc/ResultSetImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcUtils.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/MetadataResultSet.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/metadata/DatabaseMetaData.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/JdbcUtilsTest.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/metadata/DatabaseMetaDataTest.java
- Fixes problem with data type name conversion in `DatabaseMetaData`. 
- Fixes problem with missing LZ4 library in shaded jars 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2282
> [jdbc-v2] Fixed getting database metadata

- CHANGELOG.md
- examples/client-v2/pom.xml
- examples/client/pom.xml
- examples/demo-kotlin-service/build.gradle.kts
- examples/demo-kotlin-service/gradle.properties
- examples/demo-service/gradle.properties
- examples/jdbc/pom.xml
- examples/r2dbc/clickhouse-r2dbc-spring-webflux-sample/pom.xml
- pom.xml
- release.sh
Updates change log and revisions 
> Preparation 0.8.3

- jdbc-v2/src/main/java/com/clickhouse/jdbc/ResultSetImpl.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java
Adding test to try reproduce the issue 
Closes #2266 
> Adding issue #2266 tests

- .github/workflows/analysis.yml
- jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
This PR addresses a build failure by adding the missing import for ResultSetMetaData.
Fixes build issues by adding the necessary import.
> [repo] fixed missing import

- performance/src/main/java/com/clickhouse/benchmark/clients/BenchmarkBase.java
- performance/src/main/java/com/clickhouse/benchmark/clients/ConcurrentInsertClient.java
- performance/src/main/java/com/clickhouse/benchmark/clients/InsertClient.java
Fix difference of format in writer and insert call argument 
Closes 
> [repo] fixed benchmark for rowbinary writer

- LICENSE
Update LICENSE dates to 2025
Closes 
> Update LICENSE dates to 2025

- README.md
Add artifacts change announcement.
Closes 
> Artifacts announcements

- .github/workflows/run_examples.yml
> added new workflow to run examples in ci

- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataType.java
- client-v2/src/test/java/com/clickhouse/client/datatypes/DataTypeTests.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcUtils.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/metadata/DatabaseMetaDataTest.java
There is a new types `Time` and `Time64`. This PR fixes only tests and adds verification test for unknown types (to not miss one). 
There will be separate PR for missing types support implementation. 
Closes 
> [jdbc, client] Fix tests for unknown type

- performance/README.md
- performance/pom.xml
- performance/src/main/java/com/clickhouse/benchmark/BenchmarkRunner.java
- performance/src/main/java/com/clickhouse/benchmark/TestEnvironment.java
- performance/src/main/java/com/clickhouse/benchmark/clients/BenchmarkBase.java
- performance/src/main/java/com/clickhouse/benchmark/clients/Compression.java
- performance/src/main/java/com/clickhouse/benchmark/clients/ConcurrentInsertClient.java
- performance/src/main/java/com/clickhouse/benchmark/clients/ConcurrentQueryClient.java
- performance/src/main/java/com/clickhouse/benchmark/clients/DataTypes.java
- performance/src/main/java/com/clickhouse/benchmark/clients/Deserializers.java
- performance/src/main/java/com/clickhouse/benchmark/clients/InsertClient.java
- performance/src/main/java/com/clickhouse/benchmark/clients/JDBCInsert.java
- performance/src/main/java/com/clickhouse/benchmark/clients/JDBCQuery.java
- performance/src/main/java/com/clickhouse/benchmark/clients/MixedWorkload.java
- performance/src/main/java/com/clickhouse/benchmark/clients/QueryClient.java
- performance/src/main/java/com/clickhouse/benchmark/clients/Serializers.java
- performance/src/main/java/com/clickhouse/benchmark/data/ClickHouseDataTypesShort.java
- performance/src/main/java/com/clickhouse/benchmark/data/DataSet.java
- performance/src/main/java/com/clickhouse/benchmark/data/DataSetGenerator.java
- performance/src/main/java/com/clickhouse/benchmark/data/DataSets.java
- performance/src/main/java/com/clickhouse/benchmark/data/FileDataSet.java
- performance/src/main/java/com/clickhouse/benchmark/data/SimpleDataSet.java
- performance/src/main/java/com/clickhouse/benchmark/data/SyntheticDataSet.java
- performance/src/main/resources/simplelogger.properties
> restore /performance

- performance/sample_dataset.sql
> add sample.sql

- pom.xml
> set release target java version

- jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
- pom.xml
> fix release

- clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataType.java
- client-v2/src/main/java/com/clickhouse/client/api/DataTypeUtils.java
- client-v2/src/main/java/com/clickhouse/client/api/data_formats/internal/AbstractBinaryFormatReader.java
- client-v2/src/main/java/com/clickhouse/client/api/sql/SQLUtils.java
- jdbc-v2/src/main/java/com/clickhouse/data/Tuple.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/WriterStatementImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcUtils.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/DataTypeTests.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/WriterStatementImplTest.java
- jdbc-v2/src/test/java/com/clickhouse/jdbc/internal/SqlParserTest.java
- Improves test coverage for the PreparedStatementImpl
- Adds missing check that all parameters are set before executing a query 
- Does simple type cast. Further work will be done later 
Closes https://github.com/ClickHouse/clickhouse-java/issues/2418
Closes #2391 
> [jdbc] Fix prepared statement impl

- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
> fix using isBlank() from newer API

- jdbc-v2/src/main/java/com/clickhouse/jdbc/StatementImpl.java
- jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcConfiguration.java
> fixed j8 compatibility

- jdbc-v2/pom.xml
- pom.xml
Extract ANTLR to properties
Closes 
> Extract ANTLR to properties

- .github/workflows/run_examples.yml
- examples/jdbc/pom.xml
updated workflow to use head or nightly build instead of latest and staging version.
> [Repo] Fix run examples workflow

- .github/workflows/run_examples.yml
- CHANGELOG.md
- examples/client-v2/pom.xml
- examples/client/pom.xml
- examples/demo-kotlin-service/gradle.properties
- examples/demo-service/gradle.properties
- examples/jdbc/pom.xml
- examples/r2dbc/clickhouse-r2dbc-spring-webflux-sample/pom.xml
- performance/pom.xml
- pom.xml
- Updates CHANGELOG
- Updates versions.
> Pre 0.9.2 

- .github/workflows/analysis.yml
- .github/workflows/benchmarks.yml
- .github/workflows/build.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/run_examples.yml
- client-v2/src/test/java/com/clickhouse/client/datatypes/DataTypeTests.java
- upgrades ch versions to latest LTS in workflows 
Closes 
> [REPO] Upgrade ch versions to latest LTS
